### ISSUE TITLE
Pinfinder won't read file because of binary.

### ISSUE THREAD

**Issue by kaylenmichelle** [gwatts/pinfinder#1]
Hi,

I am unsure how to get the pinfinder to be able to read the binary file that the pin is in. 

Here is the text from the terminal:

Last login: Wed Oct 28 12:05:06 on ttys000
Jordan-Speegles-MacBook-Pro:~ jordanspeegle$ /Users/jordanspeegle/Downloads/pinfinder\ 2 ; exit;
-bash: /Users/jordanspeegle/Downloads/pinfinder 2: cannot execute binary file
logout

[Process completed]

**Comment by gwatts** [comment]
Hi - Are you sure you downloaded the mac version and not the Linux version?  that would give you that error message

If you run `ls -l /Users/jordanspeegle/Downloads/pinfinder\ 2`it should show a size of 3244496 bytes for the mac version.

If that all looks good, then can you tell me exactly which model of Macbook Pro you're using and which version of OS X?  If it's an old machine it may not be capable of running 64 bit programs.

**Comment by gwatts** [comment]
No updates after a month, so I assume things worked in the end.
