### ISSUE TITLE
Mismatch error

### ISSUE THREAD

**Issue by MrThollo** [gwatts/pinfinder#10]
Hi! Hope you can help! I got a mismatch error when I ran pinfinder. Running the 64 bit version for Windows and an unencrypted backup.

![image](https://cloud.githubusercontent.com/assets/23712958/20586661/2483658e-b1d4-11e6-9840-f676c0ad1291.png)

Any thoughts?

**Comment by MrThollo** [comment]
Hi again! Just checking in to see if you've had a chance to look at my issue. Thanks in advance!

**Comment by MrThollo** [comment]
Hey! Thanks so much for the reply! I'll work on that this evening when I get home and get it sent to you ASAP!


Thanks again!



Antwone

________________________________

**Comment by MrThollo** [comment]
Hey again! Sorry to bother you but I got a bit hung up on the adding -diag  instructions... would you be able to clarify a bit further on how to do it? 

Thanks again!

**Comment by gwatts** [comment]
Sure - So, if you follow the current instructions for Windows, it tells you to `Drag the pinfinder icon from the Desktop to the command prompt window, and press return to run it.`

If, after you drag the icon to the command prompt window, you click on the command prompt window and type ` -diag` and then press return, you should end up running `pinfinder.exe -diag` and you'll get the zip file that's needed.

**Comment by Troph-eus** [comment]
I got the same mismatch error.  I'm on an iMac, so can you tell me what I need to do to give you the diagnostic information you need?

**Comment by gwatts** [comment]
Hopefully 1.6.0 fixes whatever was causing this; closing this issue for now as a result.
