### ISSUE TITLE
"none" shows up--using device that has restriction and that created restriction

### ISSUE THREAD

**Issue by simonelavin** [gwatts/pinfinder#100]
I just set up a screen restriction on my iphone half an hour ago, I wanted to see if the passcode function had changed so I created a passcode (my normal iphone passcode) and messed with it a few times, but then 15 minutes later when I tried to delete it evidently I had made a typo or something because I kept getting the passcode wrong.  So I followed the instructions--made a backup and ran the program, but kept getting "none".  I don't understand why!  I just updated my iphone to IOS 13.1.2--does that have something to do with it?  Also I now realize that since I had just backed up my iphone before setting the passcode, I could have just reset from the backup and been fine.  It might be a good idea to suggest that on your website.
<img width="934" alt="Screen Shot 2019-10-07 at 12 29 37 AM" src="https://user-images.githubusercontent.com/56243971/66285208-94775680-e899-11e9-9ad3-80639145fd1e.png">

**Comment by simonelavin** [comment]
sorry--now I see that ios 13 isn't supported.  hope you guys update soon :(

**Comment by soccerenforcer** [comment]
yes please update for IOS 13 this could be a lifesaver as I've just forgotten my screen time password :/

**Comment by theswimcade** [comment]
I ran into a similar issue. I have forgotten the password to Screentime which is shared by all members of our family group. I'd appreciate it if you could update to be IOS13 compatible (currently IOS 13.2). In addition, I would like to thank you, Mr. Developer, for making this as it has helped in the past! Thanks for your time 😄

**Comment by soccerenforcer** [comment]
Okay so I contacted Gwatts and it turns out on IOS 13.2.1 they don't store the restrictions password in the backups anymore so this method of finding it out won't work anymore.

**Comment by gwatts** [comment]
Closing out as there are other issues open about iOS 13; it's unlikely support for it will be added due to the data no longer being stored in the iTunes backup

**Comment by dfsljhefhjilewr** [comment]
Does iPados 17.0.1 work?
I am having the same issue

**Comment by gwatts** [comment]
@dfsljhefhjilewr no, no versions after iOS 12 is supported by pinfinder
