### ISSUE TITLE
iMac OS Catalina - screen time

### ISSUE THREAD

**Issue by Brieback** [gwatts/pinfinder#102]
Dear all,

unbelievable but true - I installed by yesterday evening new OS Catalania on my iMac and suddenly the screen time is active from the evening time till next midday. If I want to deactivate same, system is ascing for a 4 digit code - which is not known to me. Any suggestions what I could do?

Thanks
Bjoern

**Comment by se9fault** [comment]
See my comment in #101. Logging out of your iCloud account might work, AppleCare suggests to use another iCloud account if you don’t know the passcode and “share ...” is on.

Also, in the FAQ link they claim to have some way to turn off screen time passcode for all of your devices under the same iCloud account, it seems promising but I haven’t tried it out yet.

**Comment by se9fault** [comment]
Update: See #114 - the method works on MacOS Catalina as well! (tested myself)

**Comment by gwatts** [comment]
Thanks for testing and updating the ticket, @se9fault !  Will close this ticket out in favor of #114
