### ISSUE TITLE
Virustotal scan claims that this is a 

### ISSUE THREAD

**Issue by APraestegaard** [gwatts/pinfinder#108]
Hi,

Thanks for providing this tool for free!

I just wanted to be confident, that there's a natural explanation to the fact that [virustotal ](https://www.virustotal.com/gui/file/7788201d7d8d0029be30f70d1da1a6a95801dd36559b57094b53fc016f0c8d23/detection) (Acronis engine only) claims that the exe-file contains a certain "Trojan.Ekstak.cag" signature.

-Anders

**Comment by gwatts** [comment]
thanks; no idea why it would claim that - I just compile the program and upload it here.  It's actually quite easy to compile yourself, if you'd like to be 100% sure of the code you're running (the wonders of free and open source software!) - Take a look at the "Compiling this program" section for a quick start: https://github.com/gwatts/pinfinder
