### ISSUE TITLE
Support for External Backup Location

### ISSUE THREAD

**Issue by lilmissAK47** [gwatts/pinfinder#109]
Are there plans to support an external Backup Location or to change what path pinfinder is looking for the backups?

**Comment by gwatts** [comment]
If you run the program directly from terminal, you can supply a directory name to examine as an argument.  This should be the complete bath to a backup directory:

```
$ ./Downloads/pinfinder "/Users/gareth/Library/Application Support/MobileSync/Backup/83972ccb281ee9a81663721"
```

**Comment by lilmissAK47** [comment]
Thanks Gareth... while that wasn't 100% my fix ( I had a symbolic link I had to break and a little hackety hack into my keychain later... you led me towards the right place. I finally got this stupid pin revealed to me... looking for that donation button now... 👍

**Comment by gwatts** [comment]
Great to hear that it all worked out!
