### ISSUE TITLE
Installation-instructions lacking

### ISSUE THREAD

**Issue by UnitedMarsupials** [gwatts/pinfinder#11]
I get an error trying to follow the installation-instructions from the readme-file to build/install pinfinder-1.5.0:
````
# ls -l
total 3691
-rw-rw-r--  1 mi  wheel     1499 Sep 24 14:22 LICENSE
-rw-rw-r--  1 mi  wheel     3439 Sep 24 14:22 LICENSE-go-plist
-rw-rw-r--  1 mi  wheel     5929 Sep 24 14:22 README.md
drwxrwxr-x  2 mi  wheel        5 Sep 24 14:22 docs
-rw-rw-r--  1 mi  wheel    32881 Sep 24 14:22 licenses.go
-rw-rw-r--  1 mi  wheel    10197 Sep 24 14:22 pinfinder.go
-rw-rw-r--  1 mi  wheel     6398 Sep 24 14:22 pinfinder_test.go
# go install github.com/gwatts/pinfinder
can't load package: package github.com/gwatts/pinfinder: cannot find package "github.com/gwatts/pinfinder" in any of:
        /opt/go/src/github.com/gwatts/pinfinder (from $GOROOT)
        ($GOPATH not set)
# go version
go version go1.7.4 freebsd/amd64
````
Please, advise. Thank you!

**Comment by gwatts** [comment]
Part of "downloading and installing Go" is configuring a workspace directory for it to download the dependencies and build the program.  You can find instructions on how to do that on the Go website: https://golang.org/doc/code.html#Workspaces

`go install` should of been `go get` however, i will correct that.

In a pinch you can do something like:
```bash
cd ~
mkdir ~/pinfinder
cd pinfinder
mkdir src bin pkg
export GOPATH=~/pinfinder
go get github.com/gwatts/pinfinder
bin/pinfinder
```

**Comment by UnitedMarsupials** [comment]
> In a pinch you can do

Being in a pinch, I wrote a [C-program](http://aldan.algebra.com/~mi/ipin/) to do this. Fast and with OpenSSL being the only dependency...

But the new instructions work too, thanks!
