### ISSUE TITLE
macOS High Sierra

### ISSUE THREAD

**Issue by mariwe4** [gwatts/pinfinder#110]
![Screen Shot 2020-05-21 at 6 10 47 PM](https://user-images.githubusercontent.com/65740369/82611941-ae974800-9b8f-11ea-8de2-8c6e9f38a24b.png)
I feel really dumb so I'm sorry if there's a really obvious issue or if I did something wrong.

**Comment by gwatts** [comment]
Hi @mariwe4 - does iTunes show that it made a successful backup?  Once it completed iTunes show show the current time for the "Latest Backup" info

![image](https://user-images.githubusercontent.com/334535/82612265-0cc02d00-9b88-11ea-9053-b18eb79fb413.png)
