### ISSUE TITLE
Ask for help ( IOS 13 ) +Thank you xD

### ISSUE THREAD

**Issue by ms6laser** [gwatts/pinfinder#111]
Hi gwatts !! Firstly, I thank you very much for your program. This one helped me a lot because I could not reset my iphone (the problem was related to the function "located my iphone" which had to be deactivated, but which was blocked by parental control.). Anyway, I wanted to know if there was a specific date for a first IOS 13 compatible version to come out. Thank you in advance.

**Comment by gwatts** [comment]
Hi @ms6laser - glad it helped you out!

Unfortunately there are no plans for an iOS 13 compatible version of pinfinder - The code is now stored in iCloud, so it would require a complete re-write of the tool to support that, which I don't currently have the time or resources to do.
