### ISSUE TITLE
probleme

### ISSUE THREAD

**Issue by naaza35972** [gwatts/pinfinder#112]
bonsoir 
quand je télécharge le lien, que je le met dans un dossier et que je l ouvre sa m afiche pas ce qui devrai s afficger

**Comment by gwatts** [comment]
Une fois le fichier décompressé, vous devez suivre les instructions ici pour exécuter le programme https://translate.google.com/translate?sl=auto&tl=fr&u=https%3A%2F%2Fpinfinder.net%2Fwindows.html

Notez que ce programme ne fonctionnera pas pour les appareils exécutant iOS 13 ou 14.
