### ISSUE TITLE
alphabetic passcode

### ISSUE THREAD

**Issue by trouble-ish** [gwatts/pinfinder#113]
Hi!

Thank you for pinfinder.

Apparently I have previously set an alphabetic passcode, but I only can use a numeric passcode now to recover access to the app. Why is this? 

Is there any way to change keyboards in screen time app?

Thank you for your support
Susana

**Comment by gwatts** [comment]
There are two passcodes - one to unlcok the device itself so you can use it - this passcode can be variable length or alpha numeric

The other passcode is the restrictions or screen time passcode, which is used to restrict access to certain features of the phone - That passcode is always (and can only be) 4 digits.  They are separate from each other.

**Comment by trouble-ish** [comment]
Thank you for your prompt answer.

I understand what you are saying. But when I chose a password for screen time, the keyboard was alphanumeric and i chose a word. Now, the keyboard appears in numbers (see photo <img width="249" alt="Captura de ecrã 2020-07-03, às 19 06 14" src="https://user-images.githubusercontent.com/67800675/86490785-8f7c0080-bd60-11ea-9478-ea48cd67df82.png">) and I can't insert the word. 
Is there a way to open/ access a alphanumeric keyboard in screen time?

**Comment by gwatts** [comment]
Apple has never supported using anything other than a 4 digit number for screen time; i think you must be mis-remembering

**Comment by trouble-ish** [comment]
Hi!

Sorry for the late answer.

It's not true that screen time doesn't allow an alphabetic passcode, pinfinder gave me a word (check bellow).

<img width="568" alt="Captura de ecrã 2020-07-20, às 22 21 33" src="https://user-images.githubusercontent.com/67800675/87989570-27f0df80-cada-11ea-8374-40c36f13a7a2.png">

Also, this video shows an alphanumeric keyboard: https://www.youtube.com/watch?v=T9Q-_Fhifxg

<img width="857" alt="Captura de ecrã 2020-07-20, às 22 44 40" src="https://user-images.githubusercontent.com/67800675/87989808-9cc41980-cada-11ea-9b20-1450daac9c96.png">

If you can help, I would apretiate it!
Thanks
Susana

**Comment by gwatts** [comment]
closing this out; pinfinder did not given you a word - the text just rapped to the next line - pinfinder stated "need encrypted backup" - If you follow the instructions at https://pinfinder.net/, it willl tell you how to make an encrypted backup and you can try again.

To state it again - Passcodes are *always* 4 digits; the alphanumeric keyboard does not indicate you can enter anything other than digits.

**Comment by trouble-ish** [comment]
You are right :)
Thank you for saving my day!

Kind regards
