### ISSUE TITLE
iOS 13 support no longer required

### ISSUE THREAD

**Issue by OPStellar** [gwatts/pinfinder#114]
I've been a huge advocate for PINfinder for a while now, and was greatly upset when somebody upgraded my phone to iOS 13 without my permission. For most generations until iOS 13, it was the only way to recover the Screen Time or Restrictions passcode. Now, there is a new way for iOS 13:
In Screen Time, select 'Change Screen Time Passcode' and 'Forgot Passcode,' then enter the Apple ID associated with it, and the Apple ID password. It's nearly as simple as PINfinder, except it doesn't require the computer at all!

I would like to thank GWatts for his work on the tool over the generations before iOS 13. It has been a savior many times, and I wish I had money to support him.
(I am going to close this issue, but I wanted to let Garreth know about this update so it can be used to answer others' questions about iOS 13; I know how annoying and frequent it became for such questions to be asked, and tried to help handle others' issues myself, when I could.)

**Comment by gwatts** [comment]
Thanks for your long-term support, @OPStellar - you've been beyond helpful in these issues and I'm glad pinfinder helped you out!

I've updated the [FAQs](https://pinfinder.net/faq.html#ios13l) to include the information you provided.  I know that works if you setup a passcode within iOS 13, but it wasn't clear if it worked reliably if it was pre-existing.
