### ISSUE TITLE
Is iOS 12.5.1 supported by pinfinder?

### ISSUE THREAD

**Issue by timelordsora** [gwatts/pinfinder#116]
I was trying to recover the screen time password on my iPhone 6, and it kept returning with no password. Its on 12.5.1 right now. I looked back to what it supports, and the website says up till 12.4. The thing is, 12.4 is no longer signed by apple so I cant restore my phone to that. Any ideas?

**Comment by gwatts** [comment]
As far as I know, pinfinder should work with 12.5.1; Apple didn't change the format until iOS 13 - But i haven't tested it past 12.4, and I don't have any devices running that version handy at the moment.

Make sure the "encrypt iphone backup" option is definitely checked in iTunes when you take your backup though; the passcode will not be backed up unless it is for iOS 12.
