### ISSUE TITLE
restriction password: none

### ISSUE THREAD

**Issue by zdifran** [gwatts/pinfinder#117]
<img width="567" alt="Screen Shot 2021-01-30 at 3 25 34 PM" src="https://user-images.githubusercontent.com/78283133/106370548-d25e8080-630f-11eb-8864-0db4856e9f2d.png">

what do i do here?

**Comment by gwatts** [comment]
As noted in the documentation, Apple no longer store the passcode in the backup as of iOS 13 and later, so pinfinder cannot be used for those versions.

Take a look [at this question](https://pinfinder.net/faq.html#ios13) for details on other options.

**Comment by zdifran** [comment]
so what should i do? i was using Finder with a USB chord to backup my iPhone, not iTunes like the question you linked said. i don't know how to use iTunes to back up haha

**Comment by gwatts** [comment]
I was referring to the "is iOS 13 or 14 supported" question - You may be able to change the passcode directly from settings on the phone, or else use iPhone Backup Extractor which is linked from that question

**Comment by zdifran** [comment]
ohh ok, thanks!
