### ISSUE TITLE
It find non password

### ISSUE THREAD

**Issue by sydffdg** [gwatts/pinfinder#118]
![Screenshot (58)](https://user-images.githubusercontent.com/87761103/126483034-6fa9eddb-e18c-434f-a5ba-293c696bc52e.png)
Pleas help me.

**Comment by OPStellar** [comment]
What version of macOS X are you using?

**Comment by gwatts** [comment]
@OPStellar looks like Windows

@sydffdg unfortunately pinfinder can only help with backups taken from devices running iOS 7 through 12 as Apple changed the way the passcode is stored after then.

Apple have some [tips for resetting the passcode](https://support.apple.com/en-us/HT211021)

If that doesn't help, you may have luck with a commercial took such as [iPhone Backup Extractor](https://www.iphonebackupextractor.com/guides/recover-screen-time-parental-restrictions-passcode/#ios-13)

**Comment by OPStellar** [comment]
Oh, duh… no wonder I didn't recognize it, haha!
My second guess was that the iOS version was not supported. It's been a while since I tried to help troubleshoot PINfinder issues.

**Comment by sydffdg** [comment]
I habe a Windows 10 divice. Work Pinfinder with it too? 


> Am 21.07.2021 um 15:53 schrieb Sir Vyvre the Lone ***@***.***>:
> 
> Oh, duh… no wonder I didn't recognize it, haha!
> My second guess was that the iOS version was not supported. It's been a while since I tried to help troubleshoot PINfinder issues.

**Comment by gwatts** [comment]
Pinfinder will run on Windows 10, but it still can only recover the passcode for iPhones running iOS 12 and earlier.
