### ISSUE TITLE
ios help

### ISSUE THREAD

**Issue by wocky12** [gwatts/pinfinder#122]
Will this ever be updated for ios 14,15,16 etc? because it doesnt search for screen time passcode only restrictions. Unless their is any tool like this that does screen time, please help me.

**Comment by gwatts** [comment]
No, it won't be updated .. Apple changed the format, and allows it to be reset using your apple id and password now which generally renders the tool unnecessary.  See the FAQ for details: https://pinfinder.net/faq.html

**Comment by wocky12** [comment]
> No, it won't be updated .. Apple changed the format, and allows it to be reset using your apple id and password now which generally renders the tool unnecessary. See the FAQ for details: https://pinfinder.net/faq.html

yeah but my parents put it on so i cant just recover it like that.

**Comment by gwatts** [comment]
sorry; that's a conversation to have with your parents.. the tool was only ever intended to recover devices where there was literally no other option other than to wipe the device
