### ISSUE TITLE
No passcode

### ISSUE THREAD

**Issue by JaneL1** [gwatts/pinfinder#13]
Hi, 
Its very interesting that pinfinder shows  - no restrictions
But the phone requires this bloody passcode! 
0000 - tried, not working.. Actually, tried all possible combinations. 
Any idea how it can be solved please?...

**Comment by gwatts** [comment]
Hi @JaneL1 - to be clear, are you sure you're referring to the restrictions passcode - not the one to actually unlock the device and start using it?  Pinfinder can't help find the unlock code, unfortunately

**Comment by JaneL1** [comment]
yeah, of course. i wanted to erase my phone and to restore it again. and restrictions passcode was required. so i tried all possible variations  - it didnt work. so i tried pinfinder and it showed no restrictions. :/

**Comment by gwatts** [comment]
sounds very odd - Assuming you're using Windows, can you try the instructions in this comment and see if that generates some diagnostic information I can use to figure out what's going on?  https://github.com/gwatts/pinfinder/issues/10#issuecomment-269936295

**Comment by JaneL1** [comment]
Thank you for your reply :) 
I am using mac os, not windows... Will it help anyhow? :)

**Comment by gwatts** [comment]
It will, but you'll need this file which contains the Mac version :-)

https://gwatts.com/pinfinder/pinfinder-mac-1.5.1.dev1.tar.gz

**Comment by JaneL1** [comment]
well, I have re-installed the file and this time it worked :) yaaaaayyyy! 
Thanks a lot!

**Comment by gwatts** [comment]
Wow... that shouldn't of fixed anything as it really just collects more diagnostic information, but glad it's working for you!
