### ISSUE TITLE
Backup does not exist 

### ISSUE THREAD

**Issue by boodoohooloo** [gwatts/pinfinder#14]
Hi im using windows 7 and the pinfinder.exe can not find the backup file for my iphone 5s running iOS 10. I've backed up my phone with itunes and checked off backup encryption. The command prompt brings up this message: directory Apple Computer\MobileSync\Backup does not exist. I do have the backup in C:\Users\user-PC\AppData\Roaming\Apple Computer\MobileSync\Backup\f9151008a475b8a6ce537c238f72af4ba13fd53b
![capture](https://cloud.githubusercontent.com/assets/25946168/23198572/5b5a30de-f87d-11e6-8664-7860930bff47.PNG)

**Comment by gwatts** [comment]
Hi

Interesting that it's in a different location on Windows 7; I'll have to look into that

In the interim, you can actually pass that directory name directly to the pinfinder command and it should work.  ie drag pinfinder into the command prompt per the instructions and then add your directory name to the end:

```
pinfinder.exe C:\Users\user-PC\AppData\Roaming\Apple Computer\MobileSync\Backup\f9151008a475b8a6ce537c238f72af4ba13fd53b
```

**Comment by boodoohooloo** [comment]
Thanks for responding so quickly!
I just found a solution...I moved the Apple Computer folder to my desktop and was able to run the program successfully after noticing the program did not check inside my AppData folder. Worked like a charm!

![capture](https://cloud.githubusercontent.com/assets/25946168/23199703/e9cfc8c2-f884-11e6-95b9-b495fd5b35dd.PNG)

**Comment by gwatts** [comment]
Glad you found a solution that worked for you; appreciate you updating the ticket to let me know - I'll definitely add some extra directory locations to check for in the next version as you're probably not the first to have a problem, just the first to let me know ;-)
