### ISSUE TITLE
failed MSpanList_Insert......error

### ISSUE THREAD

**Issue by wvsasha** [gwatts/pinfinder#16]
I am getting the following error and data print out when trying to run your program, please advise...

Last login: Mon Mar 27 12:36:52 on ttys001
Sonjas-iMac:~ sonjaphillips$ /Applications/Utilities/pinfinder\ 2 ; exit;
PIN Finder 1.5.0
http://github.com/gwatts/pinfinder
Sync Directory: /Users/sonjaphillips/Library/Application Support/MobileSync/Backup

IOS DEVICE                                BACKUP TIME                RESTRICTIONS PASSCODE
iPad Analeigh                             Mar 27, 2017 02:03 PM EDT  failed MSpanList_Insert 0x4c9260 0x377d71271477 0x0 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x1af8d0, 0x10)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/panic.go:530 +0x90
runtime.(*mSpanList).insert(0x26dea8, 0x4c9260)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mheap.go:933 +0x293
runtime.(*mheap).freeSpanLocked(0x26d6a0, 0x4c9260, 0x100, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mheap.go:809 +0x4be
runtime.(*mheap).grow(0x26d6a0, 0x8, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mheap.go:675 +0x2a0
runtime.(*mheap).allocSpanLocked(0x26d6a0, 0x1, 0xc820001200)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mheap.go:553 +0x4e3
runtime.(*mheap).alloc_m(0x26d6a0, 0x1, 0x7, 0xc82045e600)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mheap.go:437 +0x119
runtime.(*mheap).alloc.func1()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0x700009c0bd40)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x26d6a0, 0x1, 0x10000000007, 0x1708f)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mheap.go:503 +0x63
runtime.(*mcentral).grow(0x26ec80, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mcentral.go:209 +0x93
runtime.(*mcentral).cacheSpan(0x26ec80, 0x4c90f8)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mcentral.go:89 +0x47d
runtime.(*mcache).refill(0x4004b0, 0x7, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mcache.go:119 +0xcc
runtime.mallocgc.func2()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0xc820016000)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:1048

goroutine 10 [running]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:245 fp=0xc820be9b78 sp=0xc820be9b70
runtime.mallocgc(0x60, 0x12cd40, 0x1, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/malloc.go:643 +0x869 fp=0xc820be9c50 sp=0xc820be9b78
runtime.newarray(0x12cd40, 0x54, 0xc820d4ae70)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/malloc.go:798 +0xc9 fp=0xc820be9c90 sp=0xc820be9c50
runtime.makeslice(0x124860, 0x54, 0x54, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/slice.go:32 +0x165 fp=0xc820be9ce0 sp=0xc820be9c90
crypto/hmac.New(0x1d8c58, 0xc820ce99b0, 0x4, 0x8, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/crypto/hmac/hmac.go:84 +0x159 fp=0xc820be9d70 sp=0xc820be9ce0
golang.org/x/crypto/pbkdf2.Key(0xc820ce99b0, 0x4, 0x8, 0xc820b9a590, 0x4, 0x6, 0x3e8, 0x14, 0x1d8c58, 0x0, ...)
	/Users/gareth/projects/pinfinder/src/src/golang.org/x/crypto/pbkdf2/pbkdf2.go:43 +0x71 fp=0xc820be9e60 sp=0xc820be9d70
main.findPIN.func1(0xc820b9a590, 0x4, 0x6, 0xc820b933a0, 0x14, 0x15, 0xc820b985a0, 0xc820b9a6a0, 0x9c4, 0x1388)
	/Users/gareth/projects/pinfinder/src/src/github.com/gwatts/pinfinder/pinfinder.go:257 +0x1d8 fp=0xc820be9f60 sp=0xc820be9e60
runtime.goexit()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820be9f68 sp=0xc820be9f60
created by main.findPIN
	/Users/gareth/projects/pinfinder/src/src/github.com/gwatts/pinfinder/pinfinder.go:264 +0x197

goroutine 1 [select]:
main.findPIN(0xc820b933a0, 0x14, 0x15, 0xc820b9a590, 0x4, 0x6, 0x0, 0x0, 0x0, 0x0)
	/Users/gareth/projects/pinfinder/src/src/github.com/gwatts/pinfinder/pinfinder.go:269 +0x3dd
main.main()
	/Users/gareth/projects/pinfinder/src/src/github.com/gwatts/pinfinder/pinfinder.go:366 +0xb48

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:1998 +0x1

goroutine 9 [runnable]:
crypto/hmac.(*hmac).tmpPad(0xc820d4cae0, 0xc820d3ad5c)
	/usr/local/Cellar/go/1.6.1/libexec/src/crypto/hmac/hmac.go:44
crypto/hmac.(*hmac).Sum(0xc820d4cae0, 0xc820d3ada0, 0x14, 0x14, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/crypto/hmac/hmac.go:56 +0xd0
golang.org/x/crypto/pbkdf2.Key(0xc820d386d8, 0x4, 0x8, 0xc820b9a590, 0x4, 0x6, 0x3e8, 0x14, 0x1d8c58, 0x0, ...)
	/Users/gareth/projects/pinfinder/src/src/golang.org/x/crypto/pbkdf2/pbkdf2.go:70 +0x3f0
main.findPIN.func1(0xc820b9a590, 0x4, 0x6, 0xc820b933a0, 0x14, 0x15, 0xc820b985a0, 0xc820b9a6a0, 0x0, 0x9c4)
	/Users/gareth/projects/pinfinder/src/src/github.com/gwatts/pinfinder/pinfinder.go:257 +0x1d8
created by main.findPIN
	/Users/gareth/projects/pinfinder/src/src/github.com/gwatts/pinfinder/pinfinder.go:264 +0x197

goroutine 11 [runnable]:
crypto/sha1.(*digest).Sum(0xc820d47500, 0xc820d21ba0, 0x0, 0x14, 0x54, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/crypto/sha1/sha1.go:84
crypto/hmac.(*hmac).Sum(0xc820d45680, 0xc820d21ba0, 0x14, 0x14, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/crypto/hmac/hmac.go:60 +0x2a2
golang.org/x/crypto/pbkdf2.Key(0xc820cf78f8, 0x4, 0x8, 0xc820b9a590, 0x4, 0x6, 0x3e8, 0x14, 0x1d8c58, 0x0, ...)
	/Users/gareth/projects/pinfinder/src/src/golang.org/x/crypto/pbkdf2/pbkdf2.go:70 +0x3f0
main.findPIN.func1(0xc820b9a590, 0x4, 0x6, 0xc820b933a0, 0x14, 0x15, 0xc820b985a0, 0xc820b9a6a0, 0x1388, 0x1d4c)
	/Users/gareth/projects/pinfinder/src/src/github.com/gwatts/pinfinder/pinfinder.go:257 +0x1d8
created by main.findPIN
	/Users/gareth/projects/pinfinder/src/src/github.com/gwatts/pinfinder/pinfinder.go:264 +0x197

goroutine 12 [runnable]:
crypto/sha1.(*digest).Sum(0xc820d4eb60, 0xc820d1be60, 0x0, 0x14, 0x54, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/crypto/sha1/sha1.go:84
crypto/hmac.(*hmac).Sum(0xc820d43d40, 0xc820d1be60, 0x14, 0x14, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/crypto/hmac/hmac.go:60 +0x2a2
golang.org/x/crypto/pbkdf2.Key(0xc820d18f38, 0x4, 0x8, 0xc820b9a590, 0x4, 0x6, 0x3e8, 0x14, 0x1d8c58, 0x0, ...)
	/Users/gareth/projects/pinfinder/src/src/golang.org/x/crypto/pbkdf2/pbkdf2.go:70 +0x3f0
main.findPIN.func1(0xc820b9a590, 0x4, 0x6, 0xc820b933a0, 0x14, 0x15, 0xc820b985a0, 0xc820b9a6a0, 0x1d4c, 0x2710)
	/Users/gareth/projects/pinfinder/src/src/github.com/gwatts/pinfinder/pinfinder.go:257 +0x1d8
created by main.findPIN
	/Users/gareth/projects/pinfinder/src/src/github.com/gwatts/pinfinder/pinfinder.go:264 +0x197

goroutine 13 [semacquire]:
sync.runtime_Semacquire(0xc820b9a6ac)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc820b9a6a0)
	/usr/local/Cellar/go/1.6.1/libexec/src/sync/waitgroup.go:127 +0xb4
main.(*swg).WaitChan.func1(0xc820b9a6a0, 0xc820b98600)
	/Users/gareth/projects/pinfinder/src/src/github.com/gwatts/pinfinder/pinfinder.go:232 +0x28
created by main.(*swg).WaitChan
	/Users/gareth/projects/pinfinder/src/src/github.com/gwatts/pinfinder/pinfinder.go:234 +0x5d
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by gwatts** [comment]
Recently released 1.6.0 should fix this.
