### ISSUE TITLE
iPod 5 restrictions 

### ISSUE THREAD

**Issue by memememe2489** [gwatts/pinfinder#19]
hi there my names amy
I just got to this website and I wanna get rid of my iPod 5 restrictions but I don't want to lose all my photos data apps etc 
how would I do this?

**Comment by gwatts** [comment]
Hi

It should just be a case of making a backup of your iPod to your computer using iTunes, and then downloading and running the pinfinder software found here.

Here's the full instructions; let me know if you get stuck https://github.com/gwatts/pinfinder/blob/master/README.md

Gareth

**Comment by memememe2489** [comment]
hi there, since im slightly worried at first i wanted to try this with my
ipod 4 and i did it on my mac downloaded the appropriate version and got
this message and im not sure what to do next to bust my restrictions
passcode.[image: Inline image 1]

**Comment by gwatts** [comment]
The picture didn't come through, but most likely the ipod 4 is running a version of iOS that's too old for this method to work with; i think you'll need at least iOS 7

**Comment by memememe2489** [comment]
I tried it with my iphone 5 and it gave me my pass code and somehow for my ipod5 too!! Thanks so much I love your download and service you've made its so helpful! I finally don't have to factory reset!!

**Comment by gwatts** [comment]
Glad to hear it worked out for you!  Thanks for letting me know 😄
