### ISSUE TITLE
-bash: pinfider: command not found

### ISSUE THREAD

**Issue by stefanp7** [gwatts/pinfinder#2]
**Trying to run pinfinder on OSX 10.11, iOS 9.1. Unencripted backup on iTunes.**

 **I'm fairly Unix savvy. Can't figure out why the pfinder executable does not want to run:**

CSC-Incs-MacBook-Pro:Downloads CSCInc$ pinfinder /Users/CSCInc/Library/Application\ Support/MobileSync/Backup/7e3b6154b109c0fe7572f6bf061d540ea2f29ee2
-bash: pinfider: command not found

**I can run pinfinder as follows:**

CSC-Incs-MacBook-Pro:Downloads CSCInc$ ./pinfinder
PIN Finder 1.2.0
Directory not found: /Users/CSCInc/Library/Application Support/MobileSync/Backup/.DS_Store
Usage: pinfinder  [flags] [<path to latest iTunes backup directory>]
  -nopause
    	Set to true to prevent the program pausing for input on completion
Press Enter to exit

**...so I know that pinfinder can be executed in the current directory.**

**Then I try:**

CSC-Incs-MacBook-Pro:Downloads CSCInc$ ./pinfider /Users/CSCInc/Library/Application\ Support/MobileSync/Backup/7e3b6154b109c0fe7572f6bf061d540ea2f29ee2 
-bash: ./pinfider: No such file or directory

**My path looks ok:**

CSC-Incs-MacBook-Pro:Downloads CSCInc$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin

**Comment by gwatts** [comment]
Looks like a simple typo - You can `./pinfider` instead of `./pinfinder` (missing an n)

**Comment by stefanp7** [comment]
My mistake.  Thanks!

CSC-Incs-MacBook-Pro:Downloads CSCInc$ pinfinder /Users/CSCInc/Library/Application\ Support/MobileSync/Backup/7e3b6154b109c0fe7572f6bf061d540ea2f29ee2
PIN Finder 1.2.0
Searching backup at /Users/CSCInc/Library/Application Support/MobileSync/Backup/7e3b6154b109c0fe7572f6bf061d540ea2f29ee2
Finding PIN... FOUND!
PIN number is: XXX9 (found in 723.610599ms)

**Comment by gwatts** [comment]
Glad to help :+1:
