### ISSUE TITLE
failed MSpanList_Insert

### ISSUE THREAD

**Issue by edsonchan** [gwatts/pinfinder#22]
Last login: Thu Oct 12 13:27:02 on ttys000
iMac:~ JC$ /Users/JC/Downloads/pinfinder ; exit;
failed MSpanList_Insert 0x504000 0x1bb8d4da8ddfa 0x0 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x1af8d0, 0x10)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/panic.go:530 +0x90 fp=0x7ffeefbff690 sp=0x7ffeefbff678
runtime.(*mSpanList).insert(0x26dea8, 0x504000)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mheap.go:933 +0x293 fp=0x7ffeefbff6c0 sp=0x7ffeefbff690
runtime.(*mheap).freeSpanLocked(0x26d6a0, 0x504000, 0x100, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mheap.go:809 +0x4be fp=0x7ffeefbff728 sp=0x7ffeefbff6c0
runtime.(*mheap).grow(0x26d6a0, 0x8, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mheap.go:675 +0x2a0 fp=0x7ffeefbff780 sp=0x7ffeefbff728
runtime.(*mheap).allocSpanLocked(0x26d6a0, 0x1, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mheap.go:553 +0x4e3 fp=0x7ffeefbff7d8 sp=0x7ffeefbff780
runtime.(*mheap).alloc_m(0x26d6a0, 0x1, 0x15, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mheap.go:437 +0x119 fp=0x7ffeefbff808 sp=0x7ffeefbff7d8
runtime.(*mheap).alloc.func1()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mheap.go:502 +0x41 fp=0x7ffeefbff838 sp=0x7ffeefbff808
runtime.systemstack(0x7ffeefbff858)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:307 +0xab fp=0x7ffeefbff840 sp=0x7ffeefbff838
runtime.(*mheap).alloc(0x26d6a0, 0x1, 0x10000000015, 0x1708f)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mheap.go:503 +0x63 fp=0x7ffeefbff888 sp=0x7ffeefbff840
runtime.(*mcentral).grow(0x26f2a0, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mcentral.go:209 +0x93 fp=0x7ffeefbff8f0 sp=0x7ffeefbff888
runtime.(*mcentral).cacheSpan(0x26f2a0, 0x26a308)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mcentral.go:89 +0x47d fp=0x7ffeefbff930 sp=0x7ffeefbff8f0
runtime.(*mcache).refill(0x500000, 0x15, 0x7ffeefbff998)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mcache.go:119 +0xcc fp=0x7ffeefbff968 sp=0x7ffeefbff930
runtime.mallocgc.func2()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/malloc.go:642 +0x2b fp=0x7ffeefbff988 sp=0x7ffeefbff968
runtime.systemstack(0x7ffeefbffa28)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:307 +0xab fp=0x7ffeefbff990 sp=0x7ffeefbff988
runtime.mallocgc(0x180, 0x18dd20, 0x0, 0x800000000)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/malloc.go:643 +0x869 fp=0x7ffeefbffa68 sp=0x7ffeefbff990
runtime.newobject(0x18dd20, 0x26a570)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/malloc.go:781 +0x42 fp=0x7ffeefbffa90 sp=0x7ffeefbffa68
runtime.malg(0x8000, 0x26a7e0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:2634 +0x27 fp=0x7ffeefbffac8 sp=0x7ffeefbffa90
runtime.mpreinit(0x26ab20)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/os1_darwin.go:140 +0x1f fp=0x7ffeefbffae0 sp=0x7ffeefbffac8
runtime.mcommoninit(0x26ab20)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:494 +0x105 fp=0x7ffeefbffb28 sp=0x7ffeefbffae0
runtime.schedinit()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:434 +0x79 fp=0x7ffeefbffb70 sp=0x7ffeefbffb28
runtime.rt0_go(0x7ffeefbffba8, 0x1, 0x7ffeefbffba8, 0x0, 0x0, 0x1, 0x7ffeefbffcc0, 0x0, 0x7ffeefbffcde, 0x7ffeefbffcfa, ...)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:138 +0x132 fp=0x7ffeefbffb78 sp=0x7ffeefbffb70
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by gwatts** [comment]
This is a known compatibility issue with the latest OS X - See issue #21 - I'll be releasing an updated version soon.
