### ISSUE TITLE
Y0!

### ISSUE THREAD

**Issue by vovajulev** [gwatts/pinfinder#23]
What about iOS 11?

**Comment by mpilosov** [comment]
can confirm no iOS 11 presents issues at all. recovered my password last night. 
go ahead and download it if you're running anything prior to High Sierra.

**Comment by vovajulev** [comment]
And if it not high Sierra?

**Comment by mpilosov** [comment]
Pardon?
It will work on any OS prior to High Sierra according to the developer.

Not sent from my computer.

On Nov 20, 2017, at 17:55, vovajulev <notifications@github.com<mailto:notifications@github.com>> wrote:


And if it not high Sierra?

**Comment by vovajulev** [comment]
rigth! thank you!!!!

**Comment by gwatts** [comment]
iOS 11 should work fine and High Sierra is also now supported with 1.6.0
