### ISSUE TITLE
"no passcode stored" windows 10

### ISSUE THREAD

**Issue by PotatoPixel** [gwatts/pinfinder#25]
I've been trying to figure out my restrictions passcode, all I'm getting is "no passcode stored", and the backup date. I'm on windows 10

**Comment by PotatoPixel** [comment]
here's a screenshot (censored strangely)
![pinfinder](https://user-images.githubusercontent.com/32314263/32750652-578d6a72-c891-11e7-951f-4939d6fec689.PNG)

**Comment by gwatts** [comment]
If you drop me an email (gareth@omnipotent.net <mailto:gareth@omnipotent.net>) i’ll send you the test version of 1.6 to try

**Comment by gwatts** [comment]
1.6.0 is released - Please retry with that and re-open the issue if you still have a problem.
