### ISSUE TITLE
Ios11 backup - not supported?

### ISSUE THREAD

**Issue by imapangolin** [gwatts/pinfinder#26]
Get this when running - any solution?

Last login: Mon Nov 20 06:49:45 on console
You have new mail.
/Users/Thane/Downloads/pinfinder ; exit;
FMCServer:~ Thane$ /Users/Thane/Downloads/pinfinder ; exit;
PIN Finder 1.5.0
http://github.com/gwatts/pinfinder
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x59665cb8 pc=0xbd5f5]

runtime stack:
runtime.throw(0x1c8b60, 0x2a)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/panic.go:530 +0x90 fp=0x70000feaebe0 sp=0x70000feaebc8
runtime.sigpanic()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/sigpanic_unix.go:12 +0x5a fp=0x70000feaec30 sp=0x70000feaebe0
runtime/internal/atomic.Load64(0x59665cb8, 0x59665cbe15b0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/internal/atomic/atomic_amd64x.go:26 +0x5 fp=0x70000feaec38 sp=0x70000feaec30
runtime.lfstackpop(0x26a688, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/lfstack.go:38 +0x6d fp=0x70000feaec70 sp=0x70000feaec38
runtime.getempty(0x65, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgcwork.go:341 +0x3b fp=0x70000feaeca0 sp=0x70000feaec70
runtime.(*gcWork).init(0x70000feaed40)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgcwork.go:97 +0x20 fp=0x70000feaecb8 sp=0x70000feaeca0
runtime.(*gcWork).get(0x70000feaed40, 0x700000000001)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgcwork.go:172 +0x38 fp=0x70000feaece8 sp=0x70000feaecb8
runtime.gcDrain(0x70000feaed40, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgcmark.go:831 +0x122 fp=0x70000feaed20 sp=0x70000feaece8
runtime.gchelper()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgc.go:1802 +0x7e fp=0x70000feaed70 sp=0x70000feaed20
runtime.stopm()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:1538 +0x13f fp=0x70000feaed90 sp=0x70000feaed70
runtime.findrunnable(0xc82001b500, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:1973 +0x739 fp=0x70000feaee10 sp=0x70000feaed90
runtime.schedule()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:2072 +0x24f fp=0x70000feaee48 sp=0x70000feaee10
runtime.park_m(0xc820060c00)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:2137 +0x18b fp=0x70000feaee70 sp=0x70000feaee48
runtime.mcall(0x2b9000)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:233 +0x5b fp=0x70000feaee80 sp=0x70000feaee70

goroutine 1 [runnable]:
runtime.newobject(0x1666e0, 0xc820480000)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/malloc.go:776 fp=0xc8200d9ee8 sp=0xc8200d9ee0
github.com/DHowett/go-plist.(*xmlPlistParser).parseXMLElement(0xc820072420, 0x0, 0x0, 0xc820071e70, 0x4, 0x284aa8, 0x0, 0x0, 0xc820416740)
	/Users/gareth/projects/pinfinder/src/src/github.com/DHowett/go-plist/xml.go:252 +0x431 fp=0xc8200da378 sp=0xc8200d9ee8
github.com/DHowett/go-plist.(*xmlPlistParser).parseXMLElement(0xc820072420, 0x0, 0x0, 0xc820071df4, 0x4, 0x284aa8, 0x0, 0x0, 0xc820416500)
	/Users/gareth/projects/pinfinder/src/src/github.com/DHowett/go-plist/xml.go:279 +0x1129 fp=0xc8200da808 sp=0xc8200da378
github.com/DHowett/go-plist.(*xmlPlistParser).parseXMLElement(0xc820072420, 0x0, 0x0, 0xc820070408, 0x4, 0x284aa8, 0x0, 0x0, 0x1d7edd)
	/Users/gareth/projects/pinfinder/src/src/github.com/DHowett/go-plist/xml.go:279 +0x1129 fp=0xc8200dac98 sp=0xc8200da808
github.com/DHowett/go-plist.(*xmlPlistParser).parseXMLElement(0xc820072420, 0x0, 0x0, 0xc8200703fc, 0x4, 0x284aa8, 0x0, 0x0, 0x1d7edd)
	/Users/gareth/projects/pinfinder/src/src/github.com/DHowett/go-plist/xml.go:279 +0x1129 fp=0xc8200db128 sp=0xc8200dac98
github.com/DHowett/go-plist.(*xmlPlistParser).parseXMLElement(0xc820072420, 0x0, 0x0, 0xc8200703e9, 0x5, 0xc8200d2000, 0x1, 0x4, 0xc82004b678)
	/Users/gareth/projects/pinfinder/src/src/github.com/DHowett/go-plist/xml.go:181 +0x1d7d fp=0xc8200db5b8 sp=0xc8200db128
github.com/DHowett/go-plist.(*xmlPlistParser).parseDocument(0xc820072420, 0x0, 0x0, 0x0)
	/Users/gareth/projects/pinfinder/src/src/github.com/DHowett/go-plist/xml.go:151 +0x1ec fp=0xc8200db6f0 sp=0xc8200db5b8
github.com/DHowett/go-plist.(*Decoder).Decode(0xc8200db848, 0x1216e0, 0xc8200752e0, 0x0, 0x0)
	/Users/gareth/projects/pinfinder/src/src/github.com/DHowett/go-plist/decode.go:52 +0x44a fp=0xc8200db7e8 sp=0xc8200db6f0
main.parsePlist(0xc82006a5b0, 0x6e, 0x1216e0, 0xc8200752e0, 0x0, 0x0)
	/Users/gareth/projects/pinfinder/src/src/github.com/gwatts/pinfinder/pinfinder.go:124 +0x106 fp=0xc8200db870 sp=0xc8200db7e8
main.loadBackup(0xc82006a4d0, 0x63, 0x2)
	/Users/gareth/projects/pinfinder/src/src/github.com/gwatts/pinfinder/pinfinder.go:197 +0x140 fp=0xc8200db9c8 sp=0xc8200db870
main.loadBackups(0xc82006c280, 0x3a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/gareth/projects/pinfinder/src/src/github.com/gwatts/pinfinder/pinfinder.go:186 +0x8a2 fp=0xc8200dbb98 sp=0xc8200db9c8
main.main()
	/Users/gareth/projects/pinfinder/src/src/github.com/gwatts/pinfinder/pinfinder.go:337 +0x416 fp=0xc8200dbf40 sp=0xc8200dbb98
runtime.main()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:188 +0x2b0 fp=0xc8200dbf90 sp=0xc8200dbf40
runtime.goexit()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200dbf98 sp=0xc8200dbf90

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82003afb8 sp=0xc82003afb0

goroutine 2 [force gc (idle)]:
runtime.gopark(0x1d8ff0, 0x26a2e0, 0x1994b0, 0xf, 0x14, 0x1)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:262 +0x163 fp=0xc820026758 sp=0xc820026730
runtime.goparkunlock(0x26a2e0, 0x1994b0, 0xf, 0xc820000114, 0x1)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:268 +0x54 fp=0xc820026790 sp=0xc820026758
runtime.forcegchelper()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:229 +0xb8 fp=0xc8200267c0 sp=0xc820026790
runtime.goexit()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200267c8 sp=0xc8200267c0
created by runtime.init.4
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:218 +0x2b

goroutine 18 [GC sweep wait]:
runtime.gopark(0x1d8ff0, 0x26a3e0, 0x196e40, 0xd, 0x26614, 0x1)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:262 +0x163 fp=0xc820022748 sp=0xc820022720
runtime.goparkunlock(0x26a3e0, 0x196e40, 0xd, 0x14, 0x1)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:268 +0x54 fp=0xc820022780 sp=0xc820022748
runtime.bgsweep(0xc82006a000)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgcsweep.go:63 +0xb1 fp=0xc8200227b8 sp=0xc820022780
runtime.goexit()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200227c0 sp=0xc8200227b8
created by runtime.gcenable
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgc.go:191 +0x53

goroutine 19 [finalizer wait]:
runtime.gopark(0x1d8ff0, 0x2849d0, 0x199150, 0xe, 0x14, 0x1)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:262 +0x163 fp=0xc820022f18 sp=0xc820022ef0
runtime.goparkunlock(0x2849d0, 0x199150, 0xe, 0x14, 0x1)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:268 +0x54 fp=0xc820022f50 sp=0xc820022f18
runtime.runfinq()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mfinal.go:158 +0xaa fp=0xc820022fc0 sp=0xc820022f50
runtime.goexit()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820022fc8 sp=0xc820022fc0
created by runtime.createfing
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mfinal.go:139 +0x60

goroutine 20 [GC worker (idle)]:
runtime.gopark(0xc82000a068, 0xc8200237a0, 0x1af770, 0x10, 0x14, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:262 +0x163 fp=0xc820023740 sp=0xc820023718
runtime.gcBgMarkWorker(0xc820016000)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgc.go:1402 +0xda fp=0xc8200237b8 sp=0xc820023740
runtime.goexit()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200237c0 sp=0xc8200237b8
created by runtime.gcBgMarkStartWorkers
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgc.go:1329 +0x92

goroutine 21 [GC worker (idle)]:
runtime.gopark(0xc820071eb8, 0xc820023fa0, 0x1af770, 0x10, 0x14, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:262 +0x163 fp=0xc820023f40 sp=0xc820023f18
runtime.gcBgMarkWorker(0xc820017500)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgc.go:1402 +0xda fp=0xc820023fb8 sp=0xc820023f40
runtime.goexit()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820023fc0 sp=0xc820023fb8
created by runtime.gcBgMarkStartWorkers
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgc.go:1329 +0x92

goroutine 22 [garbage collection]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:245 fp=0xc820024510 sp=0xc820024508
runtime.gcMarkTermination()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgc.go:1181 +0x136 fp=0xc820024720 sp=0xc820024510
runtime.gcMarkDone()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgc.go:1145 +0x29e fp=0xc820024740 sp=0xc820024720
runtime.gcBgMarkWorker(0xc820018a00)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgc.go:1479 +0x488 fp=0xc8200247b8 sp=0xc820024740
runtime.goexit()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200247c0 sp=0xc8200247b8
created by runtime.gcBgMarkStartWorkers
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgc.go:1329 +0x92

goroutine 23 [GC worker (idle)]:
runtime.gopark(0xc820466000, 0xc820024fa0, 0x1af770, 0x10, 0x14, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:262 +0x163 fp=0xc820024f40 sp=0xc820024f18
runtime.gcBgMarkWorker(0xc82001a000)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgc.go:1402 +0xda fp=0xc820024fb8 sp=0xc820024f40
runtime.goexit()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820024fc0 sp=0xc820024fb8
created by runtime.gcBgMarkStartWorkers
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgc.go:1329 +0x92

goroutine 24 [GC worker (idle)]:
runtime.gopark(0xc820472000, 0xc8200257a0, 0x1af770, 0x10, 0x14, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:262 +0x163 fp=0xc820025740 sp=0xc820025718
runtime.gcBgMarkWorker(0xc82001b500)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgc.go:1402 +0xda fp=0xc8200257b8 sp=0xc820025740
runtime.goexit()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200257c0 sp=0xc8200257b8
created by runtime.gcBgMarkStartWorkers
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgc.go:1329 +0x92

goroutine 25 [GC worker (idle)]:
runtime.gopark(0xc820071ea0, 0xc820025fa0, 0x1af770, 0x10, 0x14, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:262 +0x163 fp=0xc820025f40 sp=0xc820025f18
runtime.gcBgMarkWorker(0xc82001ca00)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgc.go:1402 +0xda fp=0xc820025fb8 sp=0xc820025f40
runtime.goexit()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820025fc0 sp=0xc820025fb8
created by runtime.gcBgMarkStartWorkers
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgc.go:1329 +0x92

goroutine 26 [GC worker (idle)]:
runtime.gopark(0xc820071ea8, 0xc8204587a0, 0x1af770, 0x10, 0x14, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:262 +0x163 fp=0xc820458740 sp=0xc820458718
runtime.gcBgMarkWorker(0xc82001e000)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgc.go:1402 +0xda fp=0xc8204587b8 sp=0xc820458740
runtime.goexit()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8204587c0 sp=0xc8204587b8
created by runtime.gcBgMarkStartWorkers
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgc.go:1329 +0x92

goroutine 27 [GC worker (idle)]:
runtime.gopark(0xc820071eb0, 0xc820458fa0, 0x1af770, 0x10, 0x14, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:262 +0x163 fp=0xc820458f40 sp=0xc820458f18
runtime.gcBgMarkWorker(0xc82001f500)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgc.go:1402 +0xda fp=0xc820458fb8 sp=0xc820458f40
runtime.goexit()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820458fc0 sp=0xc820458fb8
created by runtime.gcBgMarkStartWorkers
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgc.go:1329 +0x92
[signal 0xb code=0x1 addr=0x59665cb8 pc=0xbd5f5]

runtime stack:
runtime.throw(0x1c8b60, 0x2a)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/panic.go:530 +0x90 fp=0x70000fda8be0 sp=0x70000fda8bc8
runtime.sigpanic()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/sigpanic_unix.go:12 +0x5a fp=0x70000fda8c30 sp=0x70000fda8be0
runtime/internal/atomic.Load64(0x59665cb8, 0x59665cbe15b0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/internal/atomic/atomic_amd64x.go:26 +0x5 fp=0x70000fda8c38 sp=0x70000fda8c30
runtime.lfstackpop(0x26a688, 0x5e2ab)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/lfstack.go:38 +0x6d fp=0x70000fda8c70 sp=0x70000fda8c38
runtime.getempty(0x65, 0x1103)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgcwork.go:341 +0x3b fp=0x70000fda8ca0 sp=0x70000fda8c70
runtime.(*gcWork).init(0x70000fda8d40)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgcwork.go:97 +0x20 fp=0x70000fda8cb8 sp=0x70000fda8ca0
runtime.(*gcWork).get(0x70000fda8d40, 0x70000fda8d14)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgcwork.go:172 +0x38 fp=0x70000fda8ce8 sp=0x70000fda8cb8
runtime.gcDrain(0x70000fda8d40, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgcmark.go:831 +0x122 fp=0x70000fda8d20 sp=0x70000fda8ce8
runtime.gchelper()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgc.go:1802 +0x7e fp=0x70000fda8d70 sp=0x70000fda8d20
runtime.stopm()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:1538 +0x13f fp=0x70000fda8d90 sp=0x70000fda8d70
runtime.findrunnable(0xc82001a000, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:1973 +0x739 fp=0x70000fda8e10 sp=0x70000fda8d90
runtime.schedule()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:2072 +0x24f fp=0x70000fda8e48 sp=0x70000fda8e10
runtime.park_m(0xc820060a80)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:2137 +0x18b fp=0x70000fda8e70 sp=0x70000fda8e48
runtime.mcall(0x2b9000)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:233 +0x5b fp=0x70000fda8e80 sp=0x70000fda8e70
[signal 0xb code=0x1 addr=0x59665cb8 pc=0xbd5f5]

runtime stack:
runtime.throw(0x1c8b60, 0x2a)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/panic.go:530 +0x90 fp=0x70000fd25be0 sp=0x70000fd25bc8
runtime.sigpanic()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/sigpanic_unix.go:12 +0x5a fp=0x70000fd25c30 sp=0x70000fd25be0
runtime/internal/atomic.Load64(0x59665cb8, 0x59665cbe15b0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/internal/atomic/atomic_amd64x.go:26 +0x5 fp=0x70000fd25c38 sp=0x70000fd25c30
runtime.lfstackpop(0x26a688, 0xc820022b20)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/lfstack.go:38 +0x6d fp=0x70000fd25c70 sp=0x70000fd25c38
runtime.getempty(0x65, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgcwork.go:341 +0x3b fp=0x70000fd25ca0 sp=0x70000fd25c70
runtime.(*gcWork).init(0x70000fd25d40)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgcwork.go:97 +0x20 fp=0x70000fd25cb8 sp=0x70000fd25ca0
runtime.(*gcWork).get(0x70000fd25d40, 0x700000000001)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgcwork.go:172 +0x38 fp=0x70000fd25ce8 sp=0x70000fd25cb8
runtime.gcDrain(0x70000fd25d40, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgcmark.go:831 +0x122 fp=0x70000fd25d20 sp=0x70000fd25ce8
runtime.gchelper()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgc.go:1802 +0x7e fp=0x70000fd25d70 sp=0x70000fd25d20
runtime.stopm()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:1538 +0x13f fp=0x70000fd25d90 sp=0x70000fd25d70
runtime.findrunnable(0xc820016000, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:1973 +0x739 fp=0x70000fd25e10 sp=0x70000fd25d90
runtime.schedule()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:2072 +0x24f fp=0x70000fd25e48 sp=0x70000fd25e10
runtime.park_m(0xc820060600)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:2137 +0x18b fp=0x70000fd25e70 sp=0x70000fd25e48
runtime.mcall(0x2b9000)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:233 +0x5b fp=0x70000fd25e80 sp=0x70000fd25e70
[signal 0xb code=0x1 addr=0x59665cb8 pc=0xbd5f5]

runtime stack:
runtime.throw(0x1c8b60, 0x2a)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/panic.go:530 +0x90 fp=0x7fff5fbff7c0 sp=0x7fff5fbff7a8
runtime.sigpanic()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/sigpanic_unix.go:12 +0x5a fp=0x7fff5fbff810 sp=0x7fff5fbff7c0
runtime/internal/atomic.Load64(0x59665cb8, 0x59665cbe15b0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/internal/atomic/atomic_amd64x.go:26 +0x5 fp=0x7fff5fbff818 sp=0x7fff5fbff810
runtime.lfstackpop(0x26a688, 0x19a21)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/lfstack.go:38 +0x6d fp=0x7fff5fbff850 sp=0x7fff5fbff818
runtime.getempty(0x65, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgcwork.go:341 +0x3b fp=0x7fff5fbff880 sp=0x7fff5fbff850
runtime.(*gcWork).init(0x7fff5fbff920)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgcwork.go:97 +0x20 fp=0x7fff5fbff898 sp=0x7fff5fbff880
runtime.(*gcWork).get(0x7fff5fbff920, 0x7fff00000001)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgcwork.go:172 +0x38 fp=0x7fff5fbff8c8 sp=0x7fff5fbff898
runtime.gcDrain(0x7fff5fbff920, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgcmark.go:831 +0x122 fp=0x7fff5fbff900 sp=0x7fff5fbff8c8
runtime.gchelper()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgc.go:1802 +0x7e fp=0x7fff5fbff950 sp=0x7fff5fbff900
runtime.stopm()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:1538 +0x13f fp=0x7fff5fbff970 sp=0x7fff5fbff950
runtime.gcstopm()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:1739 +0x128 fp=0x7fff5fbff9a0 sp=0x7fff5fbff970
runtime.schedule()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:2036 +0x9c fp=0x7fff5fbff9d8 sp=0x7fff5fbff9a0
runtime.goschedImpl(0xc820000180)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:2152 +0x134 fp=0x7fff5fbff9f0 sp=0x7fff5fbff9d8
runtime.gopreempt_m(0xc820000180)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:2167 +0x32 fp=0x7fff5fbffa00 sp=0x7fff5fbff9f0
runtime.newstack()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/stack.go:932 +0xa8c fp=0x7fff5fbffb70 sp=0x7fff5fbffa00
runtime.morestack()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:359 +0x7f fp=0x7fff5fbffb78 sp=0x7fff5fbffb70
[signal 0xb code=0x1 addr=0x59665cb8 pc=0xbd5f5]

runtime stack:
runtime.throw(0x1c8b60, 0x2a)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/panic.go:530 +0x90 fp=0x70000ff31c10 sp=0x70000ff31bf8
runtime.sigpanic()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/sigpanic_unix.go:12 +0x5a fp=0x70000ff31c60 sp=0x70000ff31c10
runtime/internal/atomic.Load64(0x59665cb8, 0x59665cbe15b0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/internal/atomic/atomic_amd64x.go:26 +0x5 fp=0x70000ff31c68 sp=0x70000ff31c60
runtime.lfstackpop(0x26a688, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/lfstack.go:38 +0x6d fp=0x70000ff31ca0 sp=0x70000ff31c68
runtime.getempty(0x65, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgcwork.go:341 +0x3b fp=0x70000ff31cd0 sp=0x70000ff31ca0
runtime.(*gcWork).init(0x70000ff31d70)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgcwork.go:97 +0x20 fp=0x70000ff31ce8 sp=0x70000ff31cd0
runtime.(*gcWork).get(0x70000ff31d70, 0x700000000001)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgcwork.go:172 +0x38 fp=0x70000ff31d18 sp=0x70000ff31ce8
runtime.gcDrain(0x70000ff31d70, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgcmark.go:831 +0x122 fp=0x70000ff31d50 sp=0x70000ff31d18
runtime.gchelper()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgc.go:1802 +0x7e fp=0x70000ff31da0 sp=0x70000ff31d50
runtime.stopm()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:1538 +0x13f fp=0x70000ff31dc0 sp=0x70000ff31da0
runtime.findrunnable(0xc82001ca00, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:1973 +0x739 fp=0x70000ff31e40 sp=0x70000ff31dc0
runtime.schedule()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:2072 +0x24f fp=0x70000ff31e78 sp=0x70000ff31e40
runtime.mstart1()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:1105 +0x118 fp=0x70000ff31e98 sp=0x70000ff31e78
runtime.mstart()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:1065 +0x72 fp=0x70000ff31ea8 sp=0x70000ff31e98
[signal 0xb code=0x1 addr=0x59665cb8 pc=0xbd5f5]

runtime stack:
runtime.throw(0x1c8b60, 0x2a)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/panic.go:530 +0x90 fp=0x70000fe2bcc0 sp=0x70000fe2bca8
runtime.sigpanic()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/sigpanic_unix.go:12 +0x5a fp=0x70000fe2bd10 sp=0x70000fe2bcc0
runtime/internal/atomic.Load64(0x59665cb8, 0x59665cbe15b0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/internal/atomic/atomic_amd64x.go:26 +0x5 fp=0x70000fe2bd18 sp=0x70000fe2bd10
runtime.lfstackpop(0x26a688, 0x28273)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/lfstack.go:38 +0x6d fp=0x70000fe2bd50 sp=0x70000fe2bd18
runtime.getempty(0x67, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgcwork.go:341 +0x3b fp=0x70000fe2bd80 sp=0x70000fe2bd50
runtime.(*gcWork).init(0x70000fe2be38)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgcwork.go:100 +0x53 fp=0x70000fe2bd98 sp=0x70000fe2bd80
runtime.(*gcWork).get(0x70000fe2be38, 0x1)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgcwork.go:172 +0x38 fp=0x70000fe2bdc8 sp=0x70000fe2bd98
runtime.gcDrain(0x70000fe2be38, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgcmark.go:831 +0x122 fp=0x70000fe2be00 sp=0x70000fe2bdc8
runtime.gcMark(0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgc.go:1559 +0xf9 fp=0x70000fe2be60 sp=0x70000fe2be00
runtime.gcMarkTermination.func1()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mgc.go:1173 +0x23 fp=0x70000fe2be70 sp=0x70000fe2be60
runtime.systemstack(0xc820018a00)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:291 +0x79 fp=0x70000fe2be78 sp=0x70000fe2be70
runtime.mstart()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:1048 fp=0x70000fe2be80 sp=0x70000fe2be78
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...10 completed.

[Process completed]

**Comment by gwatts** [comment]
If you're using OS X High Sierra you'll need the pre-release of 1.6 i've been testing - send me an email at gareth@omnipotent.net and i'll send you a copy to test.

**Comment by imapangolin** [comment]
Thanks.  Don't worry about it I manually found the salt and hash.  I'm brute forcing the result now.  The goofy thing is I don't expect success as I didn't turn it on and nothing is really restricted.   We shall see however.
