### ISSUE TITLE
Here is my error

### ISSUE THREAD

**Issue by ssuazo669** [gwatts/pinfinder#27]
Last login: Fri Dec  1 16:30:20 on ttys000
/Users/sixtosuazo/Library/Application\ Support/MobileSync/Backup/c9f0486977bd73e358978bf51ab98eb4a6d57014/pinfinder ; exit;
Sixtos-MacBook-Pro-2:~ sixtosuazo$ /Users/sixtosuazo/Library/Application\ Support/MobileSync/Backup/c9f0486977bd73e358978bf51ab98eb4a6d57014/pinfinder ; exit;
failed MSpanList_Insert 0x404000 0x5ba48779f7fc 0x0 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x1af8d0, 0x10)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/panic.go:530 +0x90 fp=0x7ffeefbff540 sp=0x7ffeefbff528
runtime.(*mSpanList).insert(0x26dea8, 0x404000)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mheap.go:933 +0x293 fp=0x7ffeefbff570 sp=0x7ffeefbff540
runtime.(*mheap).freeSpanLocked(0x26d6a0, 0x404000, 0x100, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mheap.go:809 +0x4be fp=0x7ffeefbff5d8 sp=0x7ffeefbff570
runtime.(*mheap).grow(0x26d6a0, 0x8, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mheap.go:675 +0x2a0 fp=0x7ffeefbff630 sp=0x7ffeefbff5d8
runtime.(*mheap).allocSpanLocked(0x26d6a0, 0x1, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mheap.go:553 +0x4e3 fp=0x7ffeefbff688 sp=0x7ffeefbff630
runtime.(*mheap).alloc_m(0x26d6a0, 0x1, 0x15, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mheap.go:437 +0x119 fp=0x7ffeefbff6b8 sp=0x7ffeefbff688
runtime.(*mheap).alloc.func1()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mheap.go:502 +0x41 fp=0x7ffeefbff6e8 sp=0x7ffeefbff6b8
runtime.systemstack(0x7ffeefbff708)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:307 +0xab fp=0x7ffeefbff6f0 sp=0x7ffeefbff6e8
runtime.(*mheap).alloc(0x26d6a0, 0x1, 0x10000000015, 0x1708f)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mheap.go:503 +0x63 fp=0x7ffeefbff738 sp=0x7ffeefbff6f0
runtime.(*mcentral).grow(0x26f2a0, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mcentral.go:209 +0x93 fp=0x7ffeefbff7a0 sp=0x7ffeefbff738
runtime.(*mcentral).cacheSpan(0x26f2a0, 0x26a308)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mcentral.go:89 +0x47d fp=0x7ffeefbff7e0 sp=0x7ffeefbff7a0
runtime.(*mcache).refill(0x400000, 0x15, 0x7ffeefbff848)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mcache.go:119 +0xcc fp=0x7ffeefbff818 sp=0x7ffeefbff7e0
runtime.mallocgc.func2()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/malloc.go:642 +0x2b fp=0x7ffeefbff838 sp=0x7ffeefbff818
runtime.systemstack(0x7ffeefbff8d8)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:307 +0xab fp=0x7ffeefbff840 sp=0x7ffeefbff838
runtime.mallocgc(0x180, 0x18dd20, 0x0, 0x800000000)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/malloc.go:643 +0x869 fp=0x7ffeefbff918 sp=0x7ffeefbff840
runtime.newobject(0x18dd20, 0x26a570)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/malloc.go:781 +0x42 fp=0x7ffeefbff940 sp=0x7ffeefbff918
runtime.malg(0x8000, 0x26a7e0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:2634 +0x27 fp=0x7ffeefbff978 sp=0x7ffeefbff940
runtime.mpreinit(0x26ab20)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/os1_darwin.go:140 +0x1f fp=0x7ffeefbff990 sp=0x7ffeefbff978
runtime.mcommoninit(0x26ab20)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:494 +0x105 fp=0x7ffeefbff9d8 sp=0x7ffeefbff990
runtime.schedinit()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:434 +0x79 fp=0x7ffeefbffa20 sp=0x7ffeefbff9d8
runtime.rt0_go(0x7ffeefbffa50, 0x1, 0x7ffeefbffa50, 0x0, 0x1, 0x7ffeefbffbc0, 0x0, 0x7ffeefbffc33, 0x7ffeefbffc4f, 0x7ffeefbffc5f, ...)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:138 +0x132 fp=0x7ffeefbffa28 sp=0x7ffeefbffa20
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by gwatts** [comment]
If you haven't already, please retry with the new 1.6.0 release of pinfinder which should fix the issue.
