### ISSUE TITLE
'go get' fails

### ISSUE THREAD

**Issue by coke** [gwatts/pinfinder#29]
```
$ go get github.com/gwatts/pinfinder
# github.com/gwatts/pinfinder
go/src/github.com/gwatts/pinfinder/decrypt.go:22:30: not enough arguments in call to backup.Open
	have (string)
	want (string, string)
go/src/github.com/gwatts/pinfinder/decrypt.go:35:14: encbw.RecordById undefined (type *backup.MobileBackup has no field or method RecordById)
$ go version
go version go1.10 darwin/amd64
```

**Comment by thathu** [comment]
I have the same issue.

**Comment by amacbride** [comment]
I'm seeing it, as well. It looks as if perhaps earlier/later versions of the dependent projects were checked in?

The MobileBackup struct in ios/backup/backup.go doesn't have RecordById, and the method call in backup.Open wants a directory and a guid, not just the full path.

```
// MobileBackup encapsulates a mobile backup manifest
type MobileBackup struct {
    Dir      string
    Manifest Manifest
    Records  []Record
    Keybag   keybag.Keybag
    Version  string

    BlobKey []byte
}
```

**Comment by amacbride** [comment]
```
func Open(pathToBackups string, guid string) (*MobileBackup, error) {
```

...is being called with a single argument.

**Comment by amacbride** [comment]
Here's the offending commit to the iosbackup project:

https://github.com/gwatts/ios/commit/68a89e1d43fe134452a11711ca2feab761e715ed#diff-c1200ceabb9994d8786d2389fae289c1

**Comment by gcamp0730** [comment]
Here's what I did to make the current version work:
`cd src/github.com/gwatts/ios
git checkout origin/wip/gareth/updates
cd ../../../..
go get github.com/gwatts/pinfinder`

Everything built and worked as it should.

**Comment by gwatts** [comment]
The 1.7.0 release of Pinfinder now includes a `go.mod` file which holds the dependencies the program needs.  You need Go 1.11 or later to take advantage of it.

The quickest way now to build pinfinder, is to do the following, which will automatically download the correct versions of everything it needs to run:

```bash
cd ~
git clone https://github.com/gwatts/pinfinder.git
cd pinfinder
GO111MODULE=on go build .
./pinfinder
``
