### ISSUE TITLE
Won't Find the File

### ISSUE THREAD

**Issue by CalvinMeyer** [gwatts/pinfinder#3]
I dragged the zip file into the command prompt as specified, and it told me the system could not find the file. I'm running Windows XP

**Comment by gwatts** [comment]
did you download the 32bit version? Did you drag the .exe file out of the zip and onto the desktop first, and then drag that into the command prompt?

If so, can you take a screenshot that includes the command prompt and either attach it here, or email it to gareth@omnipotent.net?

**Comment by CalvinMeyer** [comment]
I have the 32 bit, and I did everything you just said.

![img_3079](https://cloud.githubusercontent.com/assets/16144593/11605057/9e49fa44-9abb-11e5-841e-16fcf21bf7b3.jpg)

**Comment by gwatts** [comment]
Thanks for the screenshot; that was useful - 1.3.0 was buggy at detecting the correct backup directory for Windows XP.  I've fixed that now and tested locally and released version 1.3.1

Please download 1.3.1 and let me know if that works for you - If it fails, it should now have a more useful error message (replacing that 0x4050b0 line that you received)

**Comment by CalvinMeyer** [comment]
Thank you, I downloaded the updated version, and it worked like a charm. No errors this time :). Thanks for your help
