### ISSUE TITLE
screen not wide enough for me to read my restrictions passcode

### ISSUE THREAD

**Issue by lizzieann** [gwatts/pinfinder#30]
Hey - I downloaded pinfinder for Windows (64 bit), ran the program, entered my iphone encryption password, the screen filled with information, but the screen itself wasn't wide enough for me to read all of the information - tried using my curser to extend the screen widthwise, but the screen wouldn't extend.  Help!
[Printscreen2.docx](https://github.com/gwatts/pinfinder/files/1819913/Printscreen2.docx)

**Comment by lizzieann** [comment]
Hey Gwatts - finally figured it out and sent you a donation.  Issue solved!

**Comment by gwatts** [comment]
Thanks for the donation Lizzie - Glad it helped!
