### ISSUE TITLE
need encryption password

### ISSUE THREAD

**Issue by pietervanderwulp** [gwatts/pinfinder#31]
Pinfinder replies: "need encryption password" but I did give in the correct encryption password.
If I enter a wrong encryption password it replies: "incorrect encryption password".
If I enter no encryption password ('press return to skip') it replies: "backup is encrypted".

Perhaps a silly question but if it says 'press return to skip' does this also mean I should not press the return key after entering the encryption password? Or should I (as usual) hit the return key after giving in the encryption password?

![need-encryption-password](https://user-images.githubusercontent.com/37671075/37791150-bb49be76-2e08-11e8-9b5b-e1f37ef8d3fc.jpg)

**Comment by gwatts** [comment]
You should enter the encryption password followed by the return key, so it sounds like you're doing it right.

I would try going into iTunes with your device connected and selecting the "Change Password" button (under the "Encrypt iPhone Backup" option); enter your current password and a new one, and then try giving that new password to pinfinder.

**Comment by pietervanderwulp** [comment]
I successfully changed the encryption password in iTunes (with the iPhone connected) and after that tried again with pinfinder. But it still replies 'need encryption password'. Anything else I can do/try?

**Comment by gwatts** [comment]
that seems really weird.. so, to be clear - you changed the password in iTunes, re-backed up the phone again and supplied that new password to pinfinder and it still tells you you're using an incorrect password?

Another alternative is to remove the encryption completely from the backup by unchecking the box; you have to take a new backup then which takes quite a while, but pinfinder should then not prompt you for that password at all

**Comment by andygock** [comment]
I also had the same issue with "need encryption password" when I've entered the correct itunes backups encryption passcode. When deliberately using a wrong password, I get "incorrect encryption password" instead.

So I had to perform a backup without encryption, and run it on that, and it works.

Used with iPhone SE + jailbroken iOS 9.3.3, PIN Finder 1.60, iTunes 12.8.0.150

After saying all that, it's a good tool, it works in the end, and that's what matters. Thank you.

**Comment by spants** [comment]
have the same problem with 1.7.0 and IOS 9.3.5

**Comment by Verraeter-DerKafkaeske** [comment]
Ive got the same issue. Typed in (correct) Encryption Password but it still says "need encryption password" in the "Restriction Passcode"-Column. Running on a 64 bit Windows 10 Laptop; Backup was made with an IPhone 5s running Ios. 9.3.2 in October 2016.

**Comment by lexar** [comment]
Hello,
I have the same problem with pinfinder 1.7.1 and an iPad3 running iOS 9.3.5.
What I have done:
1. Made a backup with iTunes 12.9.5.5 on Mojave 10.14.5. The checkbox for encryption was checked and greyed out - no way to disable it.
2. Found my old backup password in keychain. pinfinder could apparently encrypt my (iOS12) iPhone backup as it said "none" (correct).
3. pinfinder could apparently not encrypt the iPad with the same password, as it said "need encryption password". I checked all entries in keychain, they all used the same password.
4. In iTunes, I changed the password for the iPad backup to "test".
5. If I type "test" in pinfinder, it says "incorrect encryption password" for the iPhone and "need encryption password" for the iPad.
6. to be sure, I made a new backup from the iPad. Same result: "need encryption password"
7. if I type the iPhone-password into pinfinder, it reports "none" for the iPhone and "incorrect encryption password" for the iPad.

So I think it might be an issue with the correct password being handled incorrectly for iOS 9 backups...?
Please let me know i I should make some more tests.

**Comment by toleksiy** [comment]
Had exactly the same problem with backup of iPad with iOS 9.3.6. Problem was resolved with local back WITHOUT encryption! The Restrictions password was shown at PIN Finder version 1.7.1.
So the solution is easy. You don't need to encrypt your backups for iOS versions 9.x.x
