### ISSUE TITLE
[Request] iOS 12 compatibility 

### ISSUE THREAD

**Issue by ghost** [gwatts/pinfinder#33]

**Comment by gwatts** [comment]
On the list to look at; they definitely changed something, but i haven't installed iOS 12 as of yet

**Comment by xiaodaitao** [comment]
I'm meeting the same problem. Apple has already removed the previous file related to restriction password, which might be be renamed as something, or the file itself might been placed at somewhere else.

**Comment by ibo2ibo** [comment]
This program said supporting ios 12 https://www.iphonebackupextractor.com/guides/recover-screen-time-parental-restrictions-passcode/
and noted this
"Ensure you have an encrypted iTunes backup or an iCloud backup. If your backup isn't encrypted, the passcode won't be stored in it."
Maybe this can help you. By the way thanks for pinfinder!

**Comment by Zeta611** [comment]
@ibo2ibo 1. It's worth **$34.95** for retrieving four digits, and 2. The manual instruction given in the page says:

> **Instructions for iOS 12 and up**

> With the release of iOS 12, Apple migrated the restrictions passcode data to a more secure location on the iPhone, and one which isn't practical to share manual instructions for. It's just too complex to recover by manually, but we have built the functionality to recover Screen Time restrictions into iPhone Backup Extractor since the iOS 12 betas.

**Comment by peachQAQ** [comment]
Waiting for the support of iOS 12. 
( There's app called Google Authenticator which stopped me from resetting my iphone, cause my accounts need the verification code in this app. )

**Comment by nolanshan** [comment]
plz let me know when screen time password recovery will work. Forgot password and won't let me reset

**Comment by nolanshan** [comment]
YES BRO I GOT IT HERE YOU GO
https://deciphertools.com/blog/forgot-restrictions-passcode/ 
ABSOLUTELY FREE OF CHARGE

**Comment by Zeta611** [comment]
@nolanshan YOU SAVED THE DAY!!!

**Comment by gwatts** [comment]
I expect to have a test version of pinfinder that supports iOS 12 available in the next day or so - check back here  if you'd like to test :-)

**Comment by Zeta611** [comment]
@gwatts Glad to hear :D

**Comment by dwoods71** [comment]
Would love to test once you get iOS 12 compatibility.  I setup screentime on my daughters phone and must of fat fingered the passcode.  I even whipped her phone but the passcode keeps coming back.  Her phone is under my family sharing so i'm assuming once she signs in with her apple id, it must pull the passcode back down from icloud??

**Comment by gwatts** [comment]
Ok, for those willing to test and give feedback - Here are the links to a test version with iOS 12 support.

NOTE: You *must* make an encrypted backup of your phone in iTunes for pinfinder to be able to recover the passcode; iTunes only backs up the passcode if encryption is turned on.

* Mac: https://omnipotent.net/tmp/pinfinder-mac-1.6.3.dev1.tar.gz
* Windows 64 bit: https://omnipotent.net/tmp/pinfinder-windows-64bit-1.6.3.dev1.zip
* Windows 32 bit: https://omnipotent.net/tmp/pinfinder-windows-32bit-1.6.3.dev1.zip

I will delete the links above once the new version (1.7) is actually released.

Please leave feedback here if it works (or doesn't!) for you - Let me know which operating system you are using, and which version of iOS you tested with, please.

**Comment by MarkG76** [comment]
> Ok, for those willing to test and give feedback - Here are the links to a test version with iOS 12 support.

Working with High Sierra (10.13.5)! 
Many thanks!

**Comment by JASR** [comment]
Works on Windows 10 (1803)

Thanks!

**Comment by ibo2ibo** [comment]
Works on Sierra 10.12.6 & 12.0
Thanks!

**Comment by mkjerl2000** [comment]
Thankyou

**Comment by nomza** [comment]
Worked on PC with encrypted backup - I love you so much, thank you. Will donate tomorrow!

**Comment by peachQAQ** [comment]
> Ok, for those willing to test and give feedback - Here are the links to a test version with iOS 12 support.
> 
> NOTE: You _must_ make an encrypted backup of your phone in iTunes for pinfinder to be able to recover the passcode; iTunes only backs up the passcode if encryption is turned on.
> 
> * Mac: https://omnipotent.net/tmp/pinfinder-mac-1.6.3.dev1.tar.gz
> * Windows 64 bit: https://omnipotent.net/tmp/pinfinder-windows-64bit-1.6.3.dev1.zip
> * Windows 32 bit: https://omnipotent.net/tmp/pinfinder-windows-32bit-1.6.3.dev1.zip
> 
> I will delete the links above once the new version (1.7) is actually released.
> 
> Please leave feedback here if it works (or doesn't!) for you - Let me know which operating system you are using, and which version of iOS you tested with, please.

It works
Windows 10，1803， （10.0.17134
IOS 12.0 ( 16A366

btw, what a stupid password, and i will donate

**Comment by gwatts** [comment]
Thanks for the feedback letting me know it works for you all!  Very helpful - Just posted 1.7.0 to the site now!
