### ISSUE TITLE
Backup not found

### ISSUE THREAD

**Issue by jinp84** [gwatts/pinfinder#34]
Hi,

Just downloaded this and followed instructions to no avail.

When i open the pinfinder.exe it says:

directory C:\Users\jinsu\Appdata\Roaming\Apple Computer\MobileSync\Backup does not exist
Usage: C:\Users\jinsu\Desktop\pinfinder.exe [flags] [<path to latest iTunes backup directory>]
 -diag
                   Generate a diagnostic pinfinder-debug.zip file
  -lincense

    -nopause
         Set to true to prevent the program pausing for input on completion
Press Enter to exit

Please help..

**Comment by gwatts** [comment]
Hi

A couple of questions:

1) Does iTunes show that it backed up successfully?
2) Which version of Windows are you running?

**Comment by jinp84** [comment]
im running windows 10 and yes itunes is backed up successfully.

**Comment by gwatts** [comment]
Normally pinfinder should automatically find the Backup directory.. i must of missed some location in this case - If you can find the Backup directory on your system, you can run pinfinder manually by opening a command prompt and running `C:\Users\jinsu\Desktop\pinfinder location-of-your-Backup-directory\most-recent-backup-directory-name` - eg. `C:\Users\jinsu\Desktop\pinfinder C:\Appdata\Roaming\Apple Computer\MobileSync\Backup\abcdef1234` - where `abcdef1234` is the most recently written to directory in that Backup directory

**Comment by KMerr62** [comment]
I too having same issue.. followed your instructions from blog and its picking up the backup of the iPhone I tested first thru ibot which worked..this particular phone I was having difficulty deciphering the ones and zeros from the letters l and O in the password key because I wasn't able to copy and paste it..my backups are both located in the backup folder..
C:\users\xxxx\apple\mobilesync\backup
Both were backed up to iTunes successfully

**Comment by gwatts** [comment]
Can you retry with the latest pinfinder 1.6.1?  It should find it successfully now

**Comment by KMerr62** [comment]
I did back in August and it worked..tysvm, but now with the new screen time the exsisting restrictions code is not accepted, so once again we are back to square 1.

**Comment by gwatts** [comment]
@KMerr62 See #33 - I'll be releasing a new version that supports iOS 12 very soon

**Comment by TenzinSean** [comment]
thank you bro @gwatts i made it. it worked. i like your software. i'm path learning Golang. nice software
