### ISSUE TITLE
Invalid backup directory

### ISSUE THREAD

**Issue by Redstein51** [gwatts/pinfinder#35]
Hi

By running pinfinder manually (as backup directory was not found automatically), Pinfinder tells: Invalid backup directory as following:

C:\Users\Jonas Schnidrig>"C:\Users\Jonas Schnidrig\Apple\MobileSync\Backup\pinfinder.exe" "C:\Users\Jonas Schnidrig\Apple\MobileSync\Backup\b4af48e750735c2d2c13545a97305832cb9b6aa1"
PIN Finder 1.6.0
iOS Restrictions Passcode Finder
https://pinfinder.net

Invalid backup directory
Usage: C:\Users\Jonas Schnidrig\Apple\MobileSync\Backup\pinfinder.exe  [flags] [<path to latest iTunes backup directory>]
  -diag
        Generate a diagnostic pinfinder-debug.zip file
  -license
        Display license information
  -nopause
        Set to true to prevent the program pausing for input on completion
Press Enter to exit

What am I doing wrong?
Please help! :)

**Comment by gwatts** [comment]
Hi - I released version 1.6.1 of pinfinder that should now correctly find your backup; could you try it out and let me know if it works for you?  You can find it here https://github.com/gwatts/pinfinder/releases/tag/1.6.1

**Comment by Redstein51** [comment]
Great!
Works wih update!
Thank you

**Comment by gwatts** [comment]
Perfect; thanks for letting me know it worked for you!
