### ISSUE TITLE
Doesn't output passcode

### ISSUE THREAD

**Issue by tabuu9** [gwatts/pinfinder#36]
I accidentally forgot the restrictions password for my iPad (running 11.4.1, dunno if that isn't working) so I downloaded this and gave it a try.

For some reason, it doesn't output anything, even if run as "Sudo /Path/To/Pinfinder/pinfinder -diag"
or "sudo /path/to/pinfinder/pinfinder /path/to/backup\ folder/" or "sudo path/pinfinder /path/to/backup\ folder/ipadbackup" it doesn't work

It just outputs

[output.txt](https://github.com/gwatts/pinfinder/files/2360758/output.txt)
[sysinfo.txt](https://github.com/gwatts/pinfinder/files/2360759/sysinfo.txt)

or 

"Invalid backup directory" for the latter two

How do I solve this?

**Comment by gwatts** [comment]
Hi

Can you tell me which version of pinfinder you're using (1.6.1 was just released yesterday; hoping i didn't break something!) and which operating system?
