### ISSUE TITLE
failed to open directory - operation not permitted

### ISSUE THREAD

**Issue by jmaxprince** [gwatts/pinfinder#39]
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/44206511/47030881-aa49b400-d13c-11e8-9ac4-273e2ca4e33f.png">

**Comment by ebee777** [comment]
Why does mac still says grant "Full Disk Access" to Terminal to run pinfinder whiles I have already granted full access

**Comment by gwatts** [comment]
make sure you're granting access to "Terminal", *not* "pinfinder"
