### ISSUE TITLE
No Passcode Found

### ISSUE THREAD

**Issue by mmpco** [gwatts/pinfinder#4]
I've tried this several times and it says NO PASSCODE FOUND for my device.  I made several different backups and none of them have seemed to work.  Can someone please help me?

**Comment by gwatts** [comment]
The two main possibilities are:

1) The iTunes backup has encryption turned on; you'll need to disable that and take another backup before pinfinder will be able to see the file with the passcode in it.  More information about encrypted backups can be found here (including disabling it) https://support.apple.com/en-us/HT205220

2) There's no restrictions passcode - Are you sure you're looking to recover the restrictions passcode (found on the Settings -> General -> Restrictions page on the device) and not the unlock passcode that actually gets you into the device itself?

If neither of those seem like it's it, can you tell me which operating system, device you have and what version of IOS is on the device?  Can you also copy and paste the output from pinfinder here too - Is it definitely seeing the most recent backup when it runs?  Or is it not showing any backups at all?
