### ISSUE TITLE
no passcode shown 

### ISSUE THREAD

**Issue by katestraw64** [gwatts/pinfinder#45]
this is all that comes up please help

**Comment by katestraw64** [comment]
![screen shot 2018-11-11 at 1 44 54 pm](https://user-images.githubusercontent.com/44934517/48307766-00353e80-e5b9-11e8-8b29-ec5026e210a6.png)

**Comment by Zeta611** [comment]
Maybe the backup isn't encrypted?

**Comment by gwatts** [comment]
@katestraw64 That's an old version of pinfinder - Please download the latest version (1.7.0) - See https://pinfinder.net/

**Comment by soulpnakake** [comment]
You need to back it up normally then go into the summary in th backups section the tick ENCRYPT Local backup

**Comment by codycree2103** [comment]
I updated to ios 13.1 and it no longer works? I backed it up and it said no pin existed yet i have 6 failed attempts, will this be fixed or will i need to downgrade?

**Comment by gwatts** [comment]
See #114 for information on iOS 13
