### ISSUE TITLE
Can't open the programme

### ISSUE THREAD

**Issue by ArapilesX** [gwatts/pinfinder#46]
Hi

I have to unzip, but then I just get this in a text page:

œ˙Ì˛Äh
ÖH__PAGEZERO∏__TEXT`S`S__text__TEXTp(ï;/p(Ä__stubs__TEXTd/|d/Ä__stub_helper__TEXTÑf/4Ñf/Ä__rodata__TEXT¿j/
¿j/__typelink__TEXT¿l<Ä¿l<__itablink__TEXT@å<–@å<__gosymtab__TEXTë<ë<__gopclntab__TEXT ë<*& ë<__cstring__TEXTP∑RC_P∑R__const__TEXT†Sp>†S__unwind_info__TEXTUSÿ
US__DATA`S``SP	__got__DATA`S`Sj__nl_symbol_ptr__DATA`S`Sm__la_symbol_ptr__DATA(`SP(`So__const__DATAÄcS$ÄcS__noptrdata__DATA†áS J†áS__data__DATA¿—T®⁄¿—T__bss__DATAÄ¨U®Á__noptrbss__DATA@îW8(__common__DATAxºWH__LINKEDIT¿W ‡~D"Ä0‡~¿¿·~` Í~H(/ì\dàËïPPëPëQ°í|¯`àŸ /usr/lib/dyldƒ≤–U#B7ÜºÛ‰§«ßQ$

*(Ä‡d8<÷/usr/lib/libSystem.B.dylib&h@*)®-Ä®__DWARF∞Uá$)__zdebug_line__DWARF¿]€∞U__zdebug_pubname__DWARFõfkã^__zdebug_pubtype__DWARFh˜`ˆ___zdebug_loc__DWARFgh—W`__zdebug_ranges__DWARF8p‹<(h__zdebug_aranges__DWARF¯tro¯dj__zdebug_info__DWARFw‰rgIw‘j__zdebug_frame__DWARFﬁ-bÚﬁw__zdebug_abbrev__DWARF@ Ä≤@x__zdebug_str__DWARFÚ$Ä…Úx__zapple_names__DWARFÛÌÅ†Û›y__apple_namespac__DWARFìˇÖ$ìÔ}__zapple_types__DWARF∑ˇÖ¨‰∑Ô}__apple_objc__DWARFc‰Ü$c‘~ˇ Go build ID: "6ASxzZzMGTTuR_Wm4G3F/11Dw2NftAb5zETco_Yra/aILSy72qSXOi0IEhtb39/JnrJ16VYCTNyACJc-xUa"

etc, etc.

Can you assist?

Thanks

**Comment by ArapilesX** [comment]
Hi Gareth

I’m on iMac.

If I click on "pinfinder-mac-1.7.0.tar.gz” at this address

https://github.com/gwatts/pinfinder/releases

it downloads to my downloads and then comes up as a Winzip file. 

I do have winzip but when I unzip then it opens as what looks like coding:


œ˙Ì˛Äh
ÖH__PAGEZERO∏__TEXT`S`S__text__TEXTp(ï;/p(Ä__stubs__TEXTd/|d/Ä__stub_helper__TEXTÑf/4Ñf/Ä__rodata__TEXT¿j/

Etc.

I do really need to unlock the restrictions so any help would be greatly appreciated.

Kind Regards

**Comment by Zeta611** [comment]
Open Terminal.app and type
```
cd ~/Downloads
```

Then do
```
tar -xvzf pinfinder-mac-1.7.0.tar.gz
```

Now execute it using
```
./pinfinder
```
or perhaps just click it from the folder. (ctrl + click > open)

**Comment by gwatts** [comment]
⬆️ 👍 Zeta611's suggestion should do the trick for you :-)

**Comment by ArapilesX** [comment]
Thanks Zeta611 and Gareth

I still can't get it to work, but a mate of mine has an IT business so I'll pick his brain.

**Comment by gwatts** [comment]
I'm going to close this out for now, but feel free to re-open if you remain stuck
