### ISSUE TITLE
ios 12.1 compatibility

### ISSUE THREAD

**Issue by gschakal** [gwatts/pinfinder#47]
Does it still work with ios12.1? all i have is none but my screen time is still asking for a passcode

![image](https://user-images.githubusercontent.com/18304130/48585329-9906e980-e92c-11e8-9836-ead3724a4e60.png)

any suggestion?

**Comment by gwatts** [comment]
I've tested it with iOS 12.1 on my ipad, and it worked ok for me - Are you definitely using pinfinder 1.7.0?

**Comment by gschakal** [comment]
Thanks for your quick feedback, that's really nice.
Yes i have just crosschecked: 1.7.0 on windows 10.  
I figured out what was the issue, i did indeed not have a passcode for MY screen time but one was asked when trying to modify my children devices screen time?? After  setting one  for me and creating a new backup, pinfinder worked like a charm.
But this code was not valid when trying to modify the screen time of my child (passcode that i had never set before !!!), in this case i had to disable the screen time feature (only the disable is done with faceid or finger print and not fortunately with the passcode!!!) and then reactivate it , in this case then ios ask me a new passcode. 
In my opinion Apple has messed this up a lot !!!
Anyway I will be really glad to donate for the best solution on the net when facing restriction passcode issue!
thanks

**Comment by gwatts** [comment]
Thanks for following up @gschakal  - That makes sense.. Pinfinder can recover the passcode for the child's device, but you have to make a backup of that actual device (at least, i think that's right; i haven't fully verified the flow yet)

**Comment by TenzinSean** [comment]
hi gwatts , i have an issue with your software. it's not working in my device. can you help me ?
<img width="564" alt="screen shot 2018-11-21 at 3 20 56 pm" src="https://user-images.githubusercontent.com/21319725/48847116-13a68d80-eda1-11e8-818a-b683d488dd80.png">

**Comment by gwatts** [comment]
@TenzinSean You'll need to grant Terminal access to the disk - See https://pinfinder.net/mac.html
