### ISSUE TITLE
Returns 3-digit passcode (iOS 12.1) 

### ISSUE THREAD

**Issue by zilero** [gwatts/pinfinder#48]
![screen shot 2018-11-24 at 8 21 47 pm](https://user-images.githubusercontent.com/45324664/48975509-9d1ac180-f026-11e8-8868-409c559d928f.png)

Not too sure what's going on here, but I went to recover my pin from an iOS 12.1 backup and it shows a 3-digit code -- but the passcode is definitely 4-digits. I tried entering 0444 but that didn't work either. Does this have something to do with iOS 12.1?

**Comment by gwatts** [comment]
that's really interesting... pinfinder 1.7 literally pulls the value out of the keychain and displays it; it doesn't do anything else to it.. so i guess either there's a bug in the decryption code there, or in this case pinfinder is extracting the wrong value (or the iphone backup is just in a weird state).

I think the first thing to try would be to make a completely new/clean backup and see if that helps (let me know if it does!)

If anyone else has come across this, i'd love to hear about it too.

**Comment by zilero** [comment]
ah i see, darn... i ended up just restoring it before you replied so i guess we’ll never know. sorry about that. thanks for the prompt reply though!

On Nov 24, 2018, at 9:02 PM, Gareth Watts <notifications@github.com<mailto:notifications@github.com>> wrote:


that's really interesting... pinfinder 1.7 literally pulls the value out of the keychain and displays it; it doesn't do anything else to it.. so i guess either there's a bug in the decryption code there, or in this case pinfinder is extracting the wrong value (or the iphone backup is just in a weird state).

I think the first thing to try would be to make a completely new/clean backup and see if that helps (let me know if it does!)

If anyone else has come across this, i'd love to hear about it too.

**Comment by gwatts** [comment]
ah ok, well perhaps someone else will report something similar - Will close this issue out until then.
