### ISSUE TITLE
Found pin but still doesnt work

### ISSUE THREAD

**Issue by angelaye98** [gwatts/pinfinder#5]
I've used the pin finder and ios7hash with my latest backup (tonight at 9:52pm) and got the pin: 2580 for both. But when i put it into my phone, it doesn't work?!?? please help

**Comment by gwatts** [comment]
Hi.. that seems odd.. I can think of a few possibilities:

1) The restrictions code it's finding is for a backup of a different device, or from a different time (easy to check with the displayed output)
2) You're confusing the restrictions code with the unlock code (happens sometimes) - The unlock code is the one that gets you into the device at all; this program doesn't recover that - Just the one that limits what you can do with the device once it's unlocked (eg. which apps can be used)
3) Something is corrupt with the backup.. Though I would expect it not to find the code at all if that were the case

There are ways to modify the backup to change the code to something else (eg. "1234") and then restore the device from that backup, but that's a bit more involved and requires different tools.. I'd only try that as a last resort though.. some details here https://web.archive.org/web/20151215172825/http://thecodeisclear.in/reset-restrictions-passcode-on-ipadiphone/

**Comment by jcwright77** [comment]
excellent, saved us from having to do a clean install.

**Comment by gwatts** [comment]
No further updates from @angelaye98, so going to close this issue - Please add a comment if you need further help.

@jcwright77 - Thanks for the comment; glad it helped you out! 👍
