### ISSUE TITLE
Pinfinder didn't work for me

### ISSUE THREAD

**Issue by MelonyBe** [gwatts/pinfinder#50]

**Comment by MelonyBe** [comment]
Please help I followed all the steps including doing an encrypted backup and no passcode was found

**Comment by michaelbrundage** [comment]
Same. I got
```
IOS DEVICE                           IOS      BACKUP TIME                RESTRICTIONS PASSCODE
Michael                              12.1.2   Dec 26, 2018 09:56 PM PST  none
```
running PinFinder after building it from source. (PIN Finder 1.7.1, go version go1.11.4 darwin/amd64. Backup is encrypted.)

I added some debugging and determined that findPINFromKeychain() isn't finding the ParentalControls entry. I used irestore to try to figure this out, without success. If it matters, my device is corporate-managed (perhaps that causes some settings like ParentalControls to be stored elsewhere?).

**Comment by gwatts** [comment]
@michaelbrundage did you ever figure this out?  No idea, tbh, if managed devices store keychain data elsewhere, but would love to improve pinfinder if anyone knows the answer

**Comment by michaelbrundage** [comment]
No, I wasn't able to progress beyond that. I was able to disable Screen Time for all my kids' devices from my phone, which -- with no way to recover the passcode short of wiping my device -- seemed like an adequate workaround.

**Comment by hellukas** [comment]
![Screenshot 2019-04-25 at 13 39 54](https://user-images.githubusercontent.com/49980728/56730898-cd939280-6761-11e9-9dc4-5335193a4753.png)
it has been like this for 2h what do i do?
