### ISSUE TITLE
skipping to end

### ISSUE THREAD

**Issue by jimjongun** [gwatts/pinfinder#51]
![c__users_josie_desktop_luke s stuff_captures_pinfinder exe 12_19_2018 3_48_52 pm](https://user-images.githubusercontent.com/46009142/50250390-37f88880-03a6-11e9-8add-c0141e85ce9a.png)

the program skips to the end without giving me a chance to put in the encryption password so it doesn't find the pin.

**Comment by gwatts** [comment]
Hi - That means its literally not finding any backups that iTunes has made, which seems very odd - Are you sure iTunes successfully made a backup?  Do you have iTunes configured to store backups in a different location that pinfinder might not be aware of?
