### ISSUE TITLE
Pinfinder not finding any pins. 

### ISSUE THREAD

**Issue by Stephane6969** [gwatts/pinfinder#52]
Hi Gareth,

I have tried to run bot 17.0 and 17.1 and have not located the pins for the screen time section. 

I would be happy to donate as I have 3 kids that can only use their ipads for 1 hour a day...lol I am surer I remembered the codes but none of them seem to work!!! 

kindest regards 

Stephane 
![screen shot 2018-12-27 at 15 26 24](https://user-images.githubusercontent.com/46196662/50485125-e4142200-09eb-11e9-8e1a-ee5d08367eb0.png)

**Comment by gwatts** [comment]
Hi - Sorry I missed this!  Are you still having problems?

**Comment by ncgolf77** [comment]
I’m trying to recover a screentime pin as well and it didn’t work for me either.  Any suggestions?

**Comment by hellukas** [comment]
![Screenshot 2019-04-25 at 13 39 54](https://user-images.githubusercontent.com/49980728/56731098-4e528e80-6762-11e9-8f08-b5dd6fe1d4a0.png)
Hi! It shows me this and it doesn't do nothing else. What should i do?

**Comment by gwatts** [comment]
@hellukas per the message it displayed, you need to enable "Full Disk Access" for Terminal so that pinfinder has permission to access your iTunes backup files - Instructions for that are at https://pinfinder.net/mac.html

**Comment by ccmsrob** [comment]
Thank you so much . It works perfect for me.
