### ISSUE TITLE
IMac says File is Damaged and should be moved to Trash

### ISSUE THREAD

**Issue by kduck97** [gwatts/pinfinder#53]

**Comment by doamatto** [comment]
Have you tried re-downloading? The download may have become corrupted during the download.

**Comment by Gregstar88** [comment]
I have the same problem, re-downloaded a couple of times with the same issue.

**Comment by Gregstar88** [comment]
..following the instructions here though it does work....

https://github.com/gwatts/pinfinder/issues/99

Open Terminal from the applications/utilities menu. 
What you must do next is click and drag PinFinder into the Terminal window and hit return/enter with the window active.
After that, type the password for the encrypted backup

i.e do not do this
"Run the program by right-clicking on the pinfinder icon and selecting "Open" - you may see a warning which you'll need to accept to run the program."

**Comment by gwatts** [comment]
Closing out old issue
