### ISSUE TITLE
window wont expand to show pin

### ISSUE THREAD

**Issue by lstallan** [gwatts/pinfinder#54]
The program seems to have run successfully, but I cant expand the window to to be able to see the result

![screenshot](https://user-images.githubusercontent.com/46418488/50735850-ff7dea80-11ac-11e9-8ba9-af485ee75003.jpg)

**Comment by gwatts** [comment]
The result wraps around to the next line - In this case "needs encrypted backup" - You need to enable the "encrypt local backup" option in itunes per https://pinfinder.net/windows.html
