### ISSUE TITLE
Nothing happens! PinFinder doesn't do anything...

### ISSUE THREAD

**Issue by Frustrated1** [gwatts/pinfinder#55]
I've installed Pinfinder on my Mac OS Mojave, given it access, and also completed my encrypted iTunes back up. I'm on iOS 12. 
When I then open "Terminal" the only thing that happens is that a small window opens up, and in this widow it only says when I last logged on and what device I'm using. Nothing else. I've waited and waited to see if something else will happen, but it doesn't. I entered the passcode for my encrypted backup to see if that would help, but that only resulted in a new message that said "command not found".

I've read through the other issues listed, but none of them are the exact same problem as mine.

What's going wrong and how can I get it to work?

Thanks for your help.

**Comment by gwatts** [comment]
Rather than opening Terminal directly, just right-click on the `pinfinder` icon and select `Open` - That will automatically open a Terminal and start the program.
