### ISSUE TITLE
Why?????!!!!!!!!!!!

### ISSUE THREAD

**Issue by 2187979468** [gwatts/pinfinder#56]
Why pinfinder 1.7.0 or later not soupper linux?????????????????????

**Comment by 2187979468** [comment]
Why??????!!!!!!!

**Comment by 2187979468** [comment]
No man can tell me why?

**Comment by 2187979468** [comment]
Oh,I wnna a windows pc,I'll go to my dad's comany to use a windows pc.

**Comment by gwatts** [comment]
I'd recommend if you want to unlock your phone, and it was provided by your dad, you ask him for help.
