### ISSUE TITLE
Pinfinder asks for encryption code

### ISSUE THREAD

**Issue by hennessy1993** [gwatts/pinfinder#58]
Hello everyone.

Im forgotten my restriction code so i tried using pinfinder to find it.
Pitty enough it asks for a encryption code.
Does anybody how to solve?

[https://www.mupload.nl/img/oek8zupaev.png](url)
[https://www.mupload.nl/img/5iacehuum73nc.png](url)

**Comment by hennessy1993** [comment]
[[IMG]https://www.mupload.nl/img/j2fkhnbkbxnvq.png[/IMG]](url)

**Comment by gwatts** [comment]
If you have forgotten the password used to encrypt your backup (which you would of entered into iTunes when you first took the backup), then you'll have to erase the backup and make a new one

**Comment by hennessy1993** [comment]
I guess i didnt enter a encryption code...
How can i delete the backup?

**Comment by gwatts** [comment]
Apple has some instructions here: https://support.apple.com/en-us/HT204215

You'll to uncheck and re-select the "Encrypt iPhone Backup" option in iTunes after deleting, so you have an opportunity to enter a new password for the new abckup.

**Comment by hennessy1993** [comment]
Did delate the backup but i still cant reselect the encrypt option when i want to make a new one

**Comment by hennessy1993** [comment]
:(

**Comment by gwatts** [comment]
You might also check here: https://support.apple.com/en-us/HT205220 under "If you can’t remember the password for your encrypted backup"
