### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by bcarvell** [gwatts/pinfinder#6]
Hi, I am getting the following error:

PIN Finder 1.4.0
http://github.com/gwatts/pinfinder
Sync Directory: C:\Users\bencarvell\AppData\Roaming\Apple Computer\MobileSync\Ba
ckup

IOS DEVICE                                BACKUP TIME                RESTRICTION
S PASSCODE
 Ben's iPhone                             Aug 16, 2016 10:51 PM BST  plist: type
 mismatch: tried to decode string into value of type struct { Key []uint8 "plist
:\"RestrictionsPasswordKey\""; Salt []uint8 "plist:\"RestrictionsPasswordSalt\""
 }

Press Enter to exit

I have done two unencrypted back ups now, and tried earlier versions of Pinfinder. There is definitely still a restrictions passcode!

Thanks,

**Comment by gwatts** [comment]
That's an interesting one!  Could you email the restrictions file itself to me at gareth@omnipotent.net  (it only contains your hashed passcode, no other info) and i'll see what's causing pinfinder problems.

You should find the file on your machine at `C:\Users\bencarvell\AppData\Roaming\Apple Computer\MobileSync\Backup\398bc9c2aeeab4cb0c12ada0f52eea12cf14f40b`

**Comment by gwatts** [comment]
Closing due to lack of further info.
