### ISSUE TITLE
github.com/gwatts/ios/keychain ???

### ISSUE THREAD

**Issue by xdeng** [gwatts/pinfinder#60]
github.com/gwatts/ios/keychain   404 ???

**Comment by gwatts** [comment]
It's on a different branch of that repo, see https://github.com/gwatts/ios/tree/wip/gareth/updates/keychain

If you're building from source you'll want to make sure Go modules are turned on so the branch is fetched correctly (see the README)

**Comment by xdeng** [comment]
Thank you
