### ISSUE TITLE
about aes gcm

### ISSUE THREAD

**Issue by xdeng** [gwatts/pinfinder#61]
I have failed with the EVS_aes_256_gcm method of openssl...
Is it because Apple is not using the standard aes gcm algorithm???

**Comment by gwatts** [comment]
I haven't hit a problem with this tbh.. under what circumstances is it causing a problem with pinfinder?

Also see you filed https://github.com/dunhamsteve/ios/issues/7 which i imagine is related

**Comment by xdeng** [comment]
Thank ~ I found a project that supports iv as null on github.

**Comment by xdeng** [comment]
https://gist.github.com/networkextension/013e510e1d711ff9cd6c9f8d13f850c5     call even with NULL pointer and zero length IV

https://opensource.apple.com/source/CommonCrypto/CommonCrypto-60027/Source/API/CommonGCMCryptor.c
