### ISSUE TITLE
Ios12 screen time decryption principle

### ISSUE THREAD

**Issue by Fanny-x** [gwatts/pinfinder#62]
Ios12 screen time is how to find it in the backup, where is the password saved in the backup?

**Comment by gwatts** [comment]
For iOS 12, it's saved in the device's encrypted keychain

**Comment by Fanny-x** [comment]
So how did you decrypt the keychain from the encrypted backup? Although you have released the source code, I still want to hear you explain the principle of decryption. This is my email address: xiongqin13880402115@gmail.com

**Comment by gwatts** [comment]
Sorry; the source code is the "source of truth" here, as far as documentation goes.

I would take a look at https://github.com/gwatts/ios/blob/wip/gareth/updates/keychain/keychain.go and start there; note I also did not write the vast majority of that code; it's forked from another open source project.
