### ISSUE TITLE
Can’t work out how to use this on my iPhone?

### ISSUE THREAD

**Issue by pipdavis** [gwatts/pinfinder#63]
I can see version 1.7.1 on screen, but when I try to ‘Open’ it just refreshes that page.

**Comment by gwatts** [comment]
You need to download and run pinfinder on a desktop or laptop computer, either running Windows or Mac - You can't run it on the iPhone itself

Eg. if you have a Windows machine, take a look at https://pinfinder.net/windows.html

**Comment by pipdavis** [comment]
THANK YOU SO MUCH!!!
You are amazing xx
