### ISSUE TITLE
Will not run pinfinder on MBP

### ISSUE THREAD

**Issue by JonnyTokyo** [gwatts/pinfinder#64]
Hi there

Have followed all the advice but the programme doesn't seem to run?  Any chance of some advice to get it going and working?  

Many thanks
JT

<img width="577" alt="Screenshot 2019-03-15 at 11 20 33" src="https://user-images.githubusercontent.com/48589874/54428379-404a3080-4715-11e9-8653-64dc5a6338d8.png">

**Comment by JonnyTokyo** [comment]
Never mind - worked it out!  Thanks so much for this amazing resource.  Will send you a donation - very much deserved!

**Comment by gwatts** [comment]
Good to hear it worked for you :-)  Donation is appreciated!

**Comment by gwatts** [comment]
Also any feedback on how to make it easier to use, or documentation improvements to help others are welcome too!
