### ISSUE TITLE
Password Shows "none"

### ISSUE THREAD

**Issue by fullyspooled** [gwatts/pinfinder#65]
I have saved an encrypted backup of both my and my wife's iPhone.  Unfortunately, the application returns "none" for the passcode, but we do have one set.

We are using family sharing.

![image](https://user-images.githubusercontent.com/49175933/55369841-3ae73700-54c6-11e9-8887-4525cc49dd51.png)

**Comment by gwatts** [comment]
Did you manage to figure this out?  It should of recovered the passcode ok as long as you backup the device that has the passcode set on it, rather than the one that set the passcode originally

**Comment by VORRR** [comment]
I did everything you said but it still didnt work

**Comment by kawallo** [comment]
Same problem here.  Pinfinder finds the code for an iPad, not for an iPhone.
IOS DEVICE                           IOS      BACKUP TIME                RESTRICTIONS PASSCODE
Luigi's iPhone                       13.3     Jan 17, 2020 04:56 PM +03  none
Luigi Cavallo’s iPad              12.4.1   Jan 12, 2020 04:33 PM +03  2580

**Comment by kawallo** [comment]
Well, I see now in the pinfder doc that IOS 13 is not supported, that's why the iPhone gives "none".
