### ISSUE TITLE
no pin found

### ISSUE THREAD

**Issue by ChristieM75** [gwatts/pinfinder#66]
<img width="583" alt="Schermafbeelding 2019-04-02 om 21 51 40" src="https://user-images.githubusercontent.com/49210798/55432233-a565a900-5592-11e9-8722-cb5f5779a4b2.png">

Hello! I followed the instructions I found on Pinfinder.net but I did not succeed in finding my pincode. See the screenshot I included. Can you please advice me what to do? Thank you!

**Comment by gwatts** [comment]
This screenshot shows Terminal running, but not pinfinder - Be sure to right-click on the pinfinder icon in your Downloads folder and clicking "Open" from there
