### ISSUE TITLE
request for iOS 6.1.6 compatibility

### ISSUE THREAD

**Issue by OPStellar** [gwatts/pinfinder#67]
Hi! This has worked very quickly and efficiently for every time I have run into the issue of dealing with the restrictions and screen time roadblock. However, my mother recently proposed that I use her old iPod Touch for music so I don't have the distraction of my phone. Its most up-to-date iOS version is 6.1.6, which is older than what Pinfinder currently works with. When I attempted to run it, which went quicker than ever, it didn't even prompt me to enter the encryption code, but it also read the restrictions code as 'none,' which is not true; the restrictions are still active, and we cannot remember the code. I am running OSX 10.13.6 and iTunes 12.8.2.3; what do you suggest I do to remedy the issue? I am capable of executing any process, no matter how complex. If there's nothing you can offer, I'll reset the system _settings_, and go from there. Thanks!

**Comment by gwatts** [comment]
For iOS 6, you can't actually recover the code, - The best you can do is reset it - This guide might help you: https://www.iphonebackupextractor.com/blog/reset-ipad-iphone-restrictions-passcode/ (you can search for "How to reset restrictions PIN from an iTunes backup manually -- for free" in that guide if you don't want to pay for a tool)


I don't have plans to add support for versions of iOS older that 7 to pinfinder at this time; i imagine relatively few people would benefit and it'd be a good bit of work to do
