### ISSUE TITLE
Which phone should I run pinfinder on?

### ISSUE THREAD

**Issue by AshleyData** [gwatts/pinfinder#69]
I'm using the latest version 1.7.1.  Should I be running this on my phone (parent's phone) or my daughter's?  I was hoping I could do it on mine.

Ashley
------------------
Ashleys-iMac-2:~ ashley$ /Users/ashley/Downloads/pinfinder ; exit;
PIN Finder 1.7.1
iOS Restrictions Passcode Finder
https://pinfinder.net

Sync Directories: [/Users/ashley/Library/Application Support/MobileSync/Backup]
Scanning backups...

Some backups are encrypted; passcode recovery requires the
encryption password used with iTunes.  Press return to skip.

Enter iTunes Encryption Password: *********

Decryption may take a few minutes...

IOS DEVICE                           IOS      BACKUP TIME                RESTRICTIONS PASSCODE
Ashley’s iPhone                      12.2     Apr 21, 2019 09:55 PM PDT  none

| DID PINFINDER SAVE THE DAY?
| Please consider donating a few dollars to say thanks!
| https://pinfinder.net/donate

Press Enter to exit

**Comment by pitust** [comment]
No, you need to run it on your dauther's phone backup

**Comment by gwatts** [comment]
@pitust is exactly right; i've updated the instructions on the site now to make that clearer.
