### ISSUE TITLE
Problem with pinfinder 

### ISSUE THREAD

**Issue by price68** [gwatts/pinfinder#70]
I always encrypt backups and pinfinder always works, but I don’t know why this time I made an encrypted backup of my phone in order to know the restrictions code and this happened:
If I enter an incorrect password it obviously says incorrect.
But when I enter the right one it shows the things usually shown but in restrictions code instead of showing me 1234( for example) it shows a message that says denied access.
Does anyone know how to solve it ?
I don’t know if it is because of the iTunes version installed in my computer or because of iOS 12.3, but it doesn’t works 
Thanks for your attention 
Edit: I’m also with 17.1 version of pinfinder

**Comment by price68** [comment]
I have tried with a few mobile phones and an iPad and still says denied access. Could it be because of recent version? Because a few months ago it worked perfectly on the same devices

**Comment by gwatts** [comment]
If you've updated to Mac OS 10.14 (Mojave), you will now need to grant additional security permissions to "Terminal" so that  pinfinder can access the backup folder:

See https://pinfinder.net/mac.html

**Comment by price68** [comment]
I’m doing it in windows, with the 64 bit version

**Comment by price68** [comment]
Don’t know if I have to grant any permission in windows and how

**Comment by gwatts** [comment]
Not sure why you would of lost permissions in Windows to access the backup - You could try running pinfinder as Administrator and see if that helps

**Comment by price68** [comment]
Ok I will try that

**Comment by price68** [comment]
Could it be that I have made the backup wrong? Because I’m following the same steps and everything is right apart from the denied access message that appears in the cmd

**Comment by price68** [comment]
Sorry for disturbing you too much btw hahaha

**Comment by gwatts** [comment]
difficult to think how you'd create a backup incorrectly (though I don't use Windows personally, so my insight here is pretty limited)

You could try either deleting the current backup (iTunes -> Preferences -> Devices and select the backup you want to delete) and make another one, or create an additional user account in Windows and do a backup there instead for a safe "clean slate" approach

**Comment by price68** [comment]
Well the thing is the same I think, what I do is go to preferences to delete the previous backups, then go to my device and check the encrypted backup square and then a copy starts, what I used to do was clicking with the right button of the mouse and pressing doing a copy, maybe the way of doing it is wrong.
Sorry if I write something wrong, I’m Spanish and there are words I don’t know how to say which are related with computing.
Btw, could it be because new 12.3 iOS version ?

**Comment by price68** [comment]
Ok I worked I love you.
These days I’m really broke but I promise you that, whenever I have some money, I will make you a donation. You are the best of the best ;)

**Comment by gwatts** [comment]
Great - what did you end up having to do?
