### ISSUE TITLE
moved backup directory, so pinfinder isn't working

### ISSUE THREAD

**Issue by macleod1213** [gwatts/pinfinder#71]
The default backup drive for itunes is C, which is a SSD with not enough memory, so I changed the default drive for itunes backup to my E drive instead.  How can I get pinfinder to find my encrypted backup there?

**Comment by gwatts** [comment]
If I ever get time, I need to have pinfinder do a better job of detecting the directory in cases like yours, but in the interim you can try the following:

If you run pinfinder manually from the command prompt, you can explicitly say which directory you want it to look at - this has to be an actual backup directory though.

So, if you've moved your backup directory to `E:\backups`, for example, take a look in there (in Windows explorer), find the name of the most recent backup directory and then start `Command Prompt` and run pinfinder:

```cd Desktop
pinfinder E:\backups\ff1eb7b72f3668b864b41cdfe9bae94659c01b2d
```

where that last bit is the name of the directory you found in Windows explorer.

**Comment by macleod1213** [comment]
Thank you!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
