### ISSUE TITLE
pinfinder says Incorrect encryption password

### ISSUE THREAD

**Issue by rockers1976** [gwatts/pinfinder#72]
<img width="743" alt="Screen Shot 2019-06-03 at 9 02 24 pm" src="https://user-images.githubusercontent.com/51322192/58797447-5e07a180-8643-11e9-996c-32cf0791b839.png">

Hi there, I get "incorrect encryption password" for my most recent back up when I run pin finder. I tried changing the password via iTunes as suggested in another thread and that hasn't helped. I wonder if pin finder has picked up that I've entered the incorrect password rather than finding the pin? Any advice would be great, thank you

**Comment by taixhi** [comment]
The encryption password is immutable for backups that are already made. You'll need to create a new backup with your new password – encrypted of course. Or else, you'll need to guess the password for encryption for the backup previously made.

**Comment by gwatts** [comment]
Per @taixhi's advice, you'll need to make a new backup after removing the encryption passcode from the device if you've forgotten it - See https://support.apple.com/en-us/HT205220#help
