### ISSUE TITLE
Old screentime passcode shown

### ISSUE THREAD

**Issue by studev** [gwatts/pinfinder#75]
I have screentime set up on my phone to manage my son's use of his phone, but I've forgotten the screentime code. I've used pinfinder before - but the restrictions password I'm shown this time is an older code that got changed. 

I'm working from a new, encrypted backup, latest iPhone, iOS 12.3.1

Any ideas?

Thanks

**Comment by gwatts** [comment]
A couple of ideas (if you're still having a problem)

* Be sure to backup your son's device to recover the passcode on it, not your device (assuming you set the passcode from your device originally)
* Hit that "Backup" button again to make sure it refreshes the data
* If that doesn't help (i haven't found a case yet where it didn't), you can delete the backup and make a fresh one by going into the iTunes preferences, selecting devices and deleting the backup from there.

Hope that helps.
