### ISSUE TITLE
Hi, HELP PLEASE

### ISSUE THREAD

**Issue by Keisi111** [gwatts/pinfinder#76]
That is my mac say me. Maybe I CAN NOT SEE password my browser Iphone because it is my laptop, sorry that i don t speak english very good
Last login: Sat Jun 22 17:43:05 on ttys000
You have mail.
/Users/kasandrakalameets/Desktop/pinfinder\ 3 ; exit;
MacBook-Air-Kasandra:~ kasandrakalameets$ /Users/kasandrakalameets/Desktop/pinfinder\ 3 ; exit;
PIN Finder 1.7.1
iOS Restrictions Passcode Finder
https://pinfinder.net

Sync Directories: [/Users/kasandrakalameets/Library/Application Support/MobileSync/Backup]
Scanning backups...

Operation not permitted: Full Disk Access Required
Please grant "Full Disk Access" to Terminal to run pinfinder
See https://pinfinder.net/mac.html for help
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Процесс завершен]

**Comment by OPStellar** [comment]
It appears you will need to go into System Preferences, and go through Security & Privacy, click the lock to make changes, and allow Terminal to control your computer. Lock it, close it, and relaunch PinFinder.
Hope this helps!
Opie

**Comment by gwatts** [comment]
Thanks @OPStellar - hopefully that helped out @Keisi111 :-)
