### ISSUE TITLE
not finding a screen time passcode

### ISSUE THREAD

**Issue by ksaltzman** [gwatts/pinfinder#78]
Created an encrypted backup of my iPhone Xs yesterday and ran pinfinder (windows 64bit) on it.  Came back with "none."

thoughts?
![2019-07-09_23-07-07](https://user-images.githubusercontent.com/52759039/60996656-e4ca3100-a309-11e9-9b0d-66793d5ae54c.jpg)

**Comment by Hamilt0n** [comment]
The same thng happened to me: it showed no restriction passcode

**Comment by MONEYHILL727** [comment]
i also have the same problem
im pretty sure your both in ios 12.3.1 in which case he has probably not updated the sofware yet

**Comment by gwatts** [comment]
Pinfinder is definitely compatible with iOS 12.3.1 - If you're trying to recover the passcode for a child's device, be sure to backup that particular device, even if the passcode was originally set via a parent's device - I've found this often causes some confusion (i've updated the instructions and FAQ now to help there)

**Comment by kavinzhao** [comment]
I guess A12 might have some additional security measures implemented to prevent such password extraction. I'm also using A12 (but on iOS 13) and pinfinder shows "none" too.

**Comment by gwatts** [comment]
@kavinzhao iOS 13 doesn't appear to include the passcode in the backup itself (at least, from my testing so far) .. also see #77 

Perhaps that'll change in upcoming dev/release versions though; going to wait and see.
