### ISSUE TITLE
Don't see that Pinfinder is asking for full disc access in privacy settings

### ISSUE THREAD

**Issue by KAStClair** [gwatts/pinfinder#79]
When I go to privacy and click on the full disc access file folder, I don't see that Pinfinder, or any other application for that matter, is requesting full disc access. So I am unable to grant it.

**Comment by OPStellar** [comment]
It will be Terminal that needs full disk access. This will only be required on OSX 10.14 (Mojave) and above.

**Comment by OPStellar** [comment]
(correction to previous statement) This will only be required if you are running Mojave or newer. I haven't updated from High Sierra to Mojave, so I am not even able to request full disk access either, as that is a feature introduced with Mojave.

**Comment by gwatts** [comment]
If you're not running Mac OS Mojave (10.14 or later), then you do not need to enable full disk access - You can check which version you are running by clicking the Apple  button at the top left of the screen and selecting "About this Mac"

If you are running Mojave, then you will need to click the "+" button on the "Full Disk Access" system preference and browse to the Utilities folder to find "Terminal" - it won't request it automatically.
