### ISSUE TITLE
unexpected signal during runtime execution

### ISSUE THREAD

**Issue by dishaias** [gwatts/pinfinder#8]
RESTRICTIONS PASSCODE
iPhone                                    Oct  4, 2016 10:32 PM IST  fatal error: unexpected signal during runtime execution

fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x2be3f4b0 pc=0xbd5f5]

**Comment by gwatts** [comment]
that's a new one - does it happen every time?  what operating system and hardware are you running it on?

**Comment by gwatts** [comment]
Closing due to lack of further information; feel free to add to this one or open another if you come across it again
