### ISSUE TITLE
Are you planning to make a pinfinder for ios 12.3.1?

### ISSUE THREAD

**Issue by MONEYHILL727** [gwatts/pinfinder#80]
because currently when i run pinfinder it says none

**Comment by gwatts** [comment]
Pinfinder is definitely already compatible with iOS 12.3.1 - Are you trying to recover the passcode for a child's device?  Be sure to backup that particular device, rather than the parent's device, if so

**Comment by MONEYHILL727** [comment]
thank you, was using the parent device insted of the childs
