### ISSUE TITLE
Pinfinder encryption

### ISSUE THREAD

**Issue by evernickie** [gwatts/pinfinder#82]
I ran back up with and without encryption but neither one will give me the restriction code. 
This is what I got ... 
I don't know what to do now, short of resetting everything

![Screenshot (310)](https://user-images.githubusercontent.com/53510058/62192316-00d65680-b33b-11e9-9fcf-1d573995c611.png)

**Comment by OPStellar** [comment]
All of them should be encrypted, preferably with the same encryption password. Then, all of them should be readable by PINFinder.
If you have any more problems, don't hesitate to bring it up! The last thing we would want is for you to resort to resetting, because we can find a way!
