### ISSUE TITLE
Pinfinder does not give me the pin and instead says "Access is denied"

### ISSUE THREAD

**Issue by Nanchuman** [gwatts/pinfinder#83]
I ran Pinfinder on Windows 10 with my encrypted backup, but it didn't particularly specify my passcode.

Here's a screenshot:
![Screenshot (104)](https://user-images.githubusercontent.com/53581543/62323208-a254c980-b45b-11e9-8bb0-3aa4d27d330f.png)

I really appreciate the help I receive. Thank you all!

**Comment by doamatto** [comment]
Try saving Pinfinder to your desktop. Temporary files usually don't have too many privileges (since you probably used "Open" on Microsoft Edge)

**Comment by gwatts** [comment]
Yeah; hopefully running as admin fixed this for you
