### ISSUE TITLE
Pinfinder not working 

### ISSUE THREAD

**Issue by em2468** [gwatts/pinfinder#84]
Pinfinder is saying "incorrect" where it should show the password on the windows version. I recently updated my phone, is it not yet compatible with ios 12.4? When will it become compatible?

**Comment by gwatts** [comment]
Pinfinder is compatible with iOS 12.4 - Are you sure it's not saying `incorrect encryption password` ?  Pinfinder needs to know what password you supplied to iTunes when creating the original backup, so it can decrypt it and find the code
