### ISSUE TITLE
Three-digit password (iOS 12.4)

### ISSUE THREAD

**Issue by Lsmirnov1989** [gwatts/pinfinder#87]
![image](https://user-images.githubusercontent.com/54213143/63213817-6a1adf80-c119-11e9-8912-736517caddc8.png)
Created a backup several times on my iPhone SE, returns a three-digit code. Used to work fine before. Adding a leading zero doesn't help.

**Comment by gwatts** [comment]
that seems very strange - First thing i'd try is deleting the backup in iTunes (which you can do from the preferences screen) and taking a fresh backup to see if something got corrupted.

**Comment by OPStellar** [comment]
(Or just move it out of the backups folder, so in the case that you need it again later it won't be gone.)

**Comment by Lsmirnov1989** [comment]
> that seems very strange - First thing i'd try is deleting the backup in iTunes (which you can do from the preferences screen) and taking a fresh backup to see if something got corrupted.

I've tried it a few times, as OPStellar advised, it didn't help.

**Comment by 7imp** [comment]
I also got this

**Comment by OPStellar** [comment]
Sorry, I'm a stickler for not losing data while troubleshooting.
You can try it without taking my route. Reproducing the issue is the first step toward solving it.
I have an iPhone SE, but somebody close to me took the liberty of updating it to iOS 13, so I'm sorry I can't help more.

**Comment by gwatts** [comment]
Closing as I've never seen anyway to reproduce this; if anyone can reproduce it feel free to re-open
