### ISSUE TITLE
Reporting a bug issue

### ISSUE THREAD

**Issue by nikki336** [gwatts/pinfinder#9]
After running pinfinder it asked me to please file a bug report because it failed to find a pin for backup.
product name        Iphone 6s
product type          iphone 8.1
product version     10.0.2
not sure how much information you need to resolve this problem?  Info is in the cmd screen.
I don't know how to copy to clipboard to capture the cmd screen with all the information>  Please advise.  Thank you.

**Comment by gwatts** [comment]
@nikki336 i don't see a description with your bug report; do you have more details?

**Comment by nikki336** [comment]
product name Iphone 6s
product type iphone 8.1
product version 10.0.2.
<?xml version="1.0 encoding="UTF-8"?>
<!DOCTYPE plIst PUBLIC "-//Apple//DTD PLIST 1.0//en" "http://www,apple.com/DTDs/
PropertyList-1.0.dtd">
<plist version-"1.0">
<dict>
           <key>RestrictionsPasswordKey</key>
           </data>
           mgtS67wzhE/676dyvc819xufZ3w=
          </data>
          qUo4gA==  
          </data>
</dict>
</plist>

**Comment by nikki336** [comment]
I sent the full report?

**Comment by nikki336** [comment]
gwatts      @nikki336 i don't see a description with your bug report; do you have more details?

product name Iphone 6s
product type iphone 8.1
product version 10.0.2.
<?xml version="1.0 encoding="UTF-8"?>
<!DOCTYPE plIst PUBLIC "-//Apple//DTD PLIST 1.0//en" "http://www,apple.com/DTDs/
PropertyList-1.0.dtd">


RestrictionsPasswordKey

mgtS67wzhE/676dyvc819xufZ3w=

qUo4gA==
please advise

**Comment by nikki336** [comment]
Failed to find Pin for backup C:\ 'Sharla's Toy'\AppData\Roaming\Apple Computer\MobileSync\Backup\2d937e4cf127377cb848a12315c11150895f89cPlease file a bug report at https://github.com/geatts/pin finder/issuesThis is the top portion I didn't send to you with my initial report.  The portion I sent you didn't have this info.  I hope this helps to resolve my issues.  Please let me know if you need anymore info.  I captured a photo if you need that.Thank youSharla Sent from XFINITY Connect Mobile App------ Original Message ------From: SharlaTo: gwatts/pinfinderSent: October 22, 2016 at 9:23 AMSubject: Re: [gwatts/pinfinder] Reporting a bug issue (#9)gwatts @nikki336 i don't see a description with your bug report; do you have more details?product name Iphone 6sproduct type iphone 8.1product version 10.0.2.<?xml version="1.0 encoding="UTF-8"?><!DOCTYPE plIst PUBLIC "-//Apple//DTD PLIST 1.0//en" "http://www,apple.com/DTDs/PropertyList-1.0.dtd">RestrictionsPasswordKeymgtS67wzhE/676dyvc819xufZ3w=qUo4gA==Thank youplease adviseFrom: "Gareth Watts" <notifications@github.com>To: "gwatts/pinfinder" <pinfinder@noreply.github.com>Cc: "nikki336" <sharla_b@comcast.net>, "Mention" <mention@noreply.github.com>Sent: Friday, October 21, 2016 9:37:34 PMSubject: Re: [gwatts/pinfinder] Reporting a bug issue (#9)@nikki336 i don't see a description with your bug report; do you have more details?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by nikki336** [comment]
gwatts @nikki336 i don't see a description with your bug report; do you have more details? 

product name Iphone 6s 
product type iphone 8.1 
product version 10.0.2. 
<?xml version="1.0 encoding="UTF-8"?> 
<!DOCTYPE plIst PUBLIC "-//Apple//DTD PLIST 1.0//en" "http://www,apple.com/DTDs/ 
PropertyList-1.0.dtd"> 

RestrictionsPasswordKey 

mgtS67wzhE/676dyvc819xufZ3w= 

qUo4gA== 




Thank you 
please advise 


----- Original Message -----

**Comment by gwatts** [comment]
Wow.

A few points:

1) This program is provided free of charge; it's written by one person (myself), in some spare time in the thought it would help some people out.  There's no guarantee that it works, but it might save you buying a commercial program or resetting your phone.

2) I maintain the program and respond to requests when I have time; I work full time and have a family, so it's not my highest priority.

3) I actually spent some time looking into your issue last night and it appears to be a corrupt file; resetting the pin is probably a better option.

Glad to hear you've figured out whatever your problem was though.
