### ISSUE TITLE
zsh: exec format error: 

### ISSUE THREAD

**Issue by takaiguchi** [gwatts/pinfinder#90]
This is what I get when I try to run Pinfinder on my Mac. 

<img width="711" alt="Screen Shot 2019-08-23 at 11 53 00 PM" src="https://user-images.githubusercontent.com/54466552/63633699-318b7200-c601-11e9-83f0-a1a214873a4e.png">

**Comment by gwatts** [comment]
not to ask a silly question, but are you sure you downloaded the mac version of pinfinder?
