### ISSUE TITLE
Encryption Passcode?

### ISSUE THREAD

**Issue by KCSaraK** [gwatts/pinfinder#91]
I have downloaded and run 1.7.0 and 1.7.1 and neither ask me for any encryption password to access the encrypted backup.  Should it be asking for this?  I have run them both for 30 minutes + and both just say "Scanning Backups" and never produce any result or error.

**Comment by KCSaraK** [comment]
Any ideas on this?  I have run an encrypted backup multiple times, and downloaded all of the versions of pinfinder. I think it's not finding the backup maybe?  I don't know how to get pinfinder to find these backups that I have run?

**Comment by gwatts** [comment]
I've not come across this issue before - It should scan the backup set pretty quickly and then ask for the encryption password

You can also try running it directly from the terminal, if you know how, and pass the name of the directory containing the backup directly to pinfinder

eg. 
```
~/Downloads/pinfinder ~/Library/Application\ Support/MobileSync/Backup/abcdcodegoeshere
```
