### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by visiblegold80** [gwatts/pinfinder#92]
pinfinder didnt work for me :(
![image](https://user-images.githubusercontent.com/55012490/64470215-6533c500-d0f4-11e9-99e2-8635ec5b920f.png)

**Comment by jacobg67** [comment]
Same issue here with ios 13.1 also

**Comment by gwatts** [comment]
As @OPStellar says, iOS 13 and 13.1 aren't supported - You might want to see my last comment on issue #77 as I added a link there to a workaround that may help.
