### ISSUE TITLE
screen time

### ISSUE THREAD

**Issue by visiblegold80** [gwatts/pinfinder#96]
willing to pay LOTS of money if someone has a way to find the screen time passcode in ios 13. dm me @gxldy on twitter if you want to talk more there as i dont use github much. need the passcode asap!

**Comment by gwatts** [comment]
As far as I am aware, there's no way currently to recover the screen time passcode for iOS 13

However checkout my last comment on this issue for a link on how to bypass it: #77 

Hope that helps
