### ISSUE TITLE
IOS 13 doesnt require pinfinder

### ISSUE THREAD

**Issue by killgame** [gwatts/pinfinder#98]
Just log out and log back in using your apple id, and screen time will be removed.

**Comment by real-acmkan** [comment]
Pinfinder is a more practical solution for when it comes to those using family sharing or those who use an Apple ID account they do not know the password of.

**Comment by AmazingIri** [comment]
No, it does not work, I tried your method out in iOS 13.1.
I did not enable "Share Across Devices", so in my opinion, your method would only work if you shared your screen time across devices; then the screen time passcode is stored together with your Apple ID.
