### ISSUE TITLE
Is this functioning right

### ISSUE THREAD

**Issue by CaitlinLyons** [gwatts/pinfinder#99]
![image](https://user-images.githubusercontent.com/56055529/66013350-da4aae00-e498-11e9-8573-793d3da56a24.jpg)
Is this functioning correctly? How long do I wait?

**Comment by OPStellar** [comment]
That is the default screen for Terminal. What you must do next is click and drag PinFinder into the Terminal window and hit return/enter with the window active.
After that, type the password for the encrypted backup. Note that PinFinder will not function if the device you are using has iOS 13 installed.
